(function(){
'use strict';
const KEY='tc_user_profile';
const GOOGLE_KEY='ngt_google_user';
const CLIENT_KEY='terracontrol_google_client_id';
function esc(v){return NGT500.esc(v||'')}
function get(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch(e){return {}}}
function first(v){return String(v||'').split(' ')[0]||''}
function render(){const p=get();const client=localStorage.getItem(CLIENT_KEY)||'';const ok=!!p.email;return `<div class="card"><h2>Konto</h2><p class="muted">Phase B.1 · Benutzerprofil und Vorbereitung für Google-Login.</p>${ok?`<div class="subcard ok">${p.picture?`<img src="${esc(p.picture)}" style="width:72px;height:72px;border-radius:50%;object-fit:cover;float:right;margin-left:12px">`:''}<b>Profil aktiv</b><br>${esc(p.name)}<br>${esc(p.email)}<br><span class="muted">Willkommen ${esc(first(p.name))}</span></div>`:`<div class="subcard"><b>Noch kein Profil gespeichert</b><br><span class="muted">Lege dein Profil an. Später wird hier die Google-Anmeldung ergänzt.</span></div>`}<div class="subcard"><h3>Lokales Profil</h3><input id="accName" placeholder="Name" value="${esc(p.name)}"><input id="accEmail" placeholder="E-Mail" value="${esc(p.email)}"><input id="accPicture" placeholder="Profilbild-URL optional" value="${esc(p.picture)}"><button onclick="NGTAccount.save()">Profil speichern</button></div><div class="subcard"><h3>Google Login Vorbereitung</h3><input id="googleClientId" placeholder="Google OAuth Client-ID" value="${esc(client)}"><button onclick="NGTAccount.saveClientId()">Client-ID speichern</button><p class="muted">Der echte Google-Button wird in Phase B.1.1 aktiviert, sobald die finale Client-ID aus der Google Cloud Console vorliegt.</p></div><div class="subcard"><h3>Cloud</h3>Google Drive Backup: <b>vorbereitet für Phase B.2</b><br>Synchronisierung: <b>geplant für Phase B.3</b></div><button class="danger" onclick="NGTAccount.clear()">Profil entfernen</button></div>`}
function save(){const name=accName.value.trim();const p={name:name,displayName:name,given_name:first(name),email:accEmail.value.trim(),picture:accPicture.value.trim(),provider:'local',updatedAt:new Date().toISOString()};localStorage.setItem(KEY,JSON.stringify(p));localStorage.setItem(GOOGLE_KEY,JSON.stringify(p));alert('Profil gespeichert.');NGT500.route('account')}
function saveClientId(){localStorage.setItem(CLIENT_KEY,googleClientId.value.trim());alert('Client-ID gespeichert.');NGT500.route('account')}
function clear(){if(confirm('Profil entfernen?')){localStorage.removeItem(KEY);localStorage.removeItem(GOOGLE_KEY);NGT500.route('account')}}
window.NGTAccount={save,saveClientId,clear};NGT500.register('account',{render});
})();