(function(){
'use strict';
const KEY='tc_user_profile';
const GOOGLE_KEY='ngt_google_user';
const CLIENT_KEY='terracontrol_google_client_id';
const DEFAULT_CLIENT='923995580181-vbtua7122vsh385e1bdp7vfuqd49m3q3.apps.googleusercontent.com';
function esc(v){return NGT500.esc(v||'')}
function get(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch(e){return {}}}
function first(v){return String(v||'').split(' ')[0]||''}
function clientId(){return localStorage.getItem(CLIENT_KEY)||DEFAULT_CLIENT}
function cloudStatus(){if(!window.NGTCloudBackup)return {};return NGTCloudBackup.status()||{}}
function syncText(){return window.NGTCloudSync?NGTCloudSync.label():'Auto-Sync lädt...'}
function syncIsOn(){return window.NGTCloudSync&&NGTCloudSync.cfg().enabled}
function render(){const p=get();const client=clientId();const ok=!!p.email;const st=cloudStatus();const last=st.lastBackupAt?new Date(st.lastBackupAt).toLocaleString('de-DE'):'Noch keine Sicherung';const lastPhoto=st.lastPhotoBackupAt?new Date(st.lastPhotoBackupAt).toLocaleString('de-DE'):'Noch keine Foto-Sicherung';return `<div class="card"><h2>Konto</h2><p class="muted">Google-Anmeldung, Benutzerprofil und TerraControl Cloud.</p>${ok?`<div class="subcard ok">${p.picture?`<img src="${esc(p.picture)}" style="width:72px;height:72px;border-radius:50%;object-fit:cover;float:right;margin-left:12px">`:''}<b>Angemeldet</b><br>${esc(p.name)}<br>${esc(p.email)}<br><span class="muted">Willkommen ${esc(first(p.given_name||p.name))}</span></div>`:`<div class="subcard"><b>Noch nicht angemeldet</b><br><span class="muted">Melde dich mit Google an oder nutze ein lokales Profil.</span></div>`}<div class="subcard"><h3>Google Login</h3><div id="googleLoginBox"><button onclick="NGTAccount.googleSignIn()">Mit Google anmelden</button></div><input id="googleClientId" placeholder="Google OAuth Client-ID" value="${esc(client)}"><button onclick="NGTAccount.saveClientId()">Client-ID speichern</button><p class="muted">Die Anmeldung speichert Name, E-Mail, Profilbild und Google-ID lokal für Cloud-Backups.</p></div><div class="subcard"><h3>TerraControl Cloud</h3><p><b>Status:</b> ${ok?'Konto verbunden':'Konto nicht verbunden'}</p><p><b>Letzte Sicherung:</b><br>${esc(last)}</p><p><b>Foto-Cloud:</b><br>${esc(lastPhoto)}${st.photoCount?` · ${esc(st.photoCount)} Fotos`:''}</p><p><b>Auto-Sync:</b><br>${esc(syncText())}</p><button onclick="NGTAccount.toggleSync()">${syncIsOn()?'Auto-Sync ausschalten':'Auto-Sync einschalten'}</button><button onclick="NGTAccount.syncNow()">Jetzt synchronisieren</button><div class="btnRow"><button onclick="NGTAccount.cloudDriveBackup()">In Google Drive sichern</button><button onclick="NGTAccount.photoBackup()">Fotos sichern</button><button onclick="NGTAccount.photoRestore()">Fotos wiederherstellen</button><button onclick="NGTAccount.cloudListDrive()">Backup-Historie</button><button onclick="NGTAccount.cloudBackup()">Datei sichern</button><button onclick="NGTAccount.cloudRestorePick()">Datei wiederherstellen</button></div><input id="cloudRestoreFile" type="file" accept="application/json,.json" style="display:none" onchange="NGTAccount.cloudRestore(this.files[0])"><div id="driveBackups"></div><p class="muted">Daten-Backups bleiben klein. Fotos werden separat als TerraControl-Photo Dateien in Google Drive gespeichert.</p></div><div class="subcard"><h3>Lokales Profil</h3><input id="accName" placeholder="Name" value="${esc(p.name)}"><input id="accEmail" placeholder="E-Mail" value="${esc(p.email)}"><input id="accPicture" placeholder="Profilbild-URL optional" value="${esc(p.picture)}"><button onclick="NGTAccount.save()">Profil speichern</button></div><button class="danger" onclick="NGTAccount.clear()">Abmelden / Profil entfernen</button></div>`}
function saveProfile(p){localStorage.setItem(KEY,JSON.stringify(p));localStorage.setItem(GOOGLE_KEY,JSON.stringify(p))}
function save(){const name=accName.value.trim();const p={name:name,displayName:name,given_name:first(name),email:accEmail.value.trim(),picture:accPicture.value.trim(),provider:'local',updatedAt:new Date().toISOString()};saveProfile(p);alert('Profil gespeichert.');NGT500.route('account')}
function saveClientId(){localStorage.setItem(CLIENT_KEY,googleClientId.value.trim());alert('Client-ID gespeichert.');NGT500.route('account')}
function clear(){if(confirm('Konto-Daten lokal entfernen?')){localStorage.removeItem(KEY);localStorage.removeItem(GOOGLE_KEY);NGT500.route('account')}}
function decodeJwt(token){try{const part=token.split('.')[1]||'';const b64=part.replace(/-/g,'+').replace(/_/g,'/');const json=decodeURIComponent(atob(b64).split('').map(c=>'%'+('00'+c.charCodeAt(0).toString(16)).slice(-2)).join(''));return JSON.parse(json)}catch(e){return {}}}
function onCredential(res){const d=decodeJwt(res&&res.credential||'');if(!d.email){alert('Google-Anmeldung konnte nicht gelesen werden.');return;}const p={name:d.name||'',displayName:d.name||'',given_name:d.given_name||first(d.name||''),family_name:d.family_name||'',email:d.email||'',picture:d.picture||'',sub:d.sub||'',provider:'google',updatedAt:new Date().toISOString()};saveProfile(p);NGT500.route('account')}
function loadGoogle(cb){if(window.google&&google.accounts&&google.accounts.id){cb();return;}const s=document.createElement('script');s.src='https://accounts.'+'google.com/gsi/client';s.async=true;s.defer=true;s.onload=cb;s.onerror=function(){alert('Google Login konnte nicht geladen werden.')};document.head.appendChild(s)}
function googleSignIn(){const cid=clientId();if(!cid){alert('Keine Client-ID hinterlegt.');return;}loadGoogle(function(){try{google.accounts.id.initialize({client_id:cid,callback:onCredential});google.accounts.id.prompt(function(n){if(n&&n.isNotDisplayed&&n.isNotDisplayed()){renderButton()}});renderButton()}catch(e){alert('Google Login Fehler: '+e.message)}})}
function renderButton(){const box=document.getElementById('googleLoginBox');if(!box||!(window.google&&google.accounts&&google.accounts.id))return;box.innerHTML='<div id="googleBtn"></div>';google.accounts.id.renderButton(document.getElementById('googleBtn'),{theme:'outline',size:'large',width:300,text:'signin_with'});}
function cloudBackup(){if(!window.NGTCloudBackup){alert('Cloud-Modul nicht geladen.');return;}NGTCloudBackup.download();alert('Cloud-Backup erstellt und als Datei gespeichert.');NGT500.route('account')}
function cloudDriveBackup(){if(!window.NGTCloudBackup){alert('Cloud-Modul nicht geladen.');return;}const box=document.getElementById('driveBackups');if(box)box.innerHTML='<div class="subcard">Google Drive Sicherung läuft...</div>';NGTCloudBackup.uploadToDrive().then(m=>{alert('Backup wurde in Google Drive gespeichert.');NGT500.route('account')}).catch(e=>{if(box)box.innerHTML='<div class="subcard danger">'+esc(e.message)+'</div>';alert(e.message)})}
function photoBackup(){if(!window.NGTCloudBackup||!NGTCloudBackup.uploadPhotos){alert('Foto-Cloud lädt noch.');return;}const box=document.getElementById('driveBackups');if(box)box.innerHTML='<div class="subcard">Fotos werden gesichert...</div>';NGTCloudBackup.uploadPhotos().then(r=>{alert('Foto-Sicherung fertig. Gesichert: '+r.uploaded+' Fotos.');NGT500.route('account')}).catch(e=>{if(box)box.innerHTML='<div class="subcard danger">'+esc(e.message)+'</div>';alert(e.message)})}
function photoRestore(){if(!window.NGTCloudBackup||!NGTCloudBackup.restorePhotos){alert('Foto-Cloud lädt noch.');return;}if(!confirm('Fotos aus Google Drive wiederherstellen?'))return;const box=document.getElementById('driveBackups');if(box)box.innerHTML='<div class="subcard">Fotos werden wiederhergestellt...</div>';NGTCloudBackup.restorePhotos().then(r=>{alert('Fotos wiederhergestellt: '+r.restored);location.reload()}).catch(e=>alert(e.message))}
function cloudListDrive(){if(!window.NGTCloudBackup){alert('Cloud-Modul nicht geladen.');return;}const box=document.getElementById('driveBackups');box.innerHTML='<div class="subcard">Backup-Historie wird geladen...</div>';NGTCloudBackup.listDriveBackups(20).then(files=>{box.innerHTML=files.length?'<div class="subcard"><h3>Backup-Historie</h3><p class="muted">'+files.length+' Backups gefunden.</p><button onclick="NGTAccount.cleanupDrive()">Nur letzte 20 behalten</button></div>'+files.map(f=>`<div class="subcard"><b>${esc(f.name)}</b><br>${esc(new Date(f.createdTime).toLocaleString('de-DE'))}<br>Größe: ${esc(NGTCloudBackup.sizeLabel(f.size))}<div class="btnRow"><button onclick="NGTAccount.restoreDrive('${esc(f.id)}')">Wiederherstellen</button><button class="danger" onclick="NGTAccount.deleteDrive('${esc(f.id)}')">Löschen</button></div></div>`).join(''):'<div class="subcard">Keine TerraControl-Backups in Google Drive gefunden.</div>'}).catch(e=>box.innerHTML='<div class="subcard danger">'+esc(e.message)+'</div>')}
function cleanupDrive(){if(!confirm('Alte Backups löschen und nur die letzten 20 behalten?'))return;NGTCloudBackup.cleanupDriveBackups(20).then(r=>{alert('Aufgeräumt. Gelöscht: '+r.deleted);cloudListDrive()}).catch(e=>alert(e.message))}
function deleteDrive(id){if(!confirm('Dieses Backup aus Google Drive löschen?'))return;NGTCloudBackup.deleteDriveFile(id).then(()=>{alert('Backup gelöscht.');cloudListDrive()}).catch(e=>alert(e.message))}
function restoreDrive(id){if(!confirm('Dieses Google-Drive-Backup wiederherstellen? Aktuelle lokale Daten können überschrieben werden.'))return;NGTCloudBackup.downloadDriveFile(id).then(obj=>{NGTCloudBackup.restoreFromObject(obj);alert('Backup wiederhergestellt. App wird neu geladen.');location.reload()}).catch(e=>alert(e.message))}
function cloudRestorePick(){document.getElementById('cloudRestoreFile').click()}
function cloudRestore(file){if(!file)return;if(!confirm('Backup wiederherstellen? Aktuelle lokale Daten können überschrieben werden.'))return;NGTCloudBackup.importFile(file).then(()=>{alert('Backup wiederhergestellt. App wird neu geladen.');location.reload()}).catch(e=>alert('Import fehlgeschlagen: '+e.message))}
function toggleSync(){if(!window.NGTCloudSync){alert('Auto-Sync lädt noch.');return;}NGTCloudSync.enable(!NGTCloudSync.cfg().enabled);NGT500.route('account')}
function syncNow(){if(!window.NGTCloudSync){alert('Auto-Sync lädt noch.');return;}NGTCloudSync.setConfig({enabled:true});NGTCloudSync.markDirty('Manuell');NGTCloudSync.syncNow().then(()=>{alert('Synchronisiert.');NGT500.route('account')}).catch(e=>alert(e.message))}
function afterRender(){if(!window.NGTCloudBackup){const c=document.createElement('script');c.src='./v500/cloud-backup.js?v=1.5';document.head.appendChild(c)}if(!window.NGTCloudSync){const y=document.createElement('script');y.src='./v500/cloud-sync.js?v=1.0';document.head.appendChild(y)}if(clientId())setTimeout(function(){loadGoogle(function(){try{google.accounts.id.initialize({client_id:clientId(),callback:onCredential});renderButton()}catch(e){}})},150)}
window.NGTAccount={save,saveClientId,clear,googleSignIn,cloudBackup,cloudDriveBackup,cloudRestorePick,cloudRestore,cloudListDrive,restoreDrive,deleteDrive,cleanupDrive,toggleSync,syncNow,photoBackup,photoRestore};NGT500.register('account',{render,afterRender});
})();