(function(){
'use strict';
const KEY='tc_user_profile';
const GOOGLE_KEY='ngt_google_user';
const CLIENT_KEY='terracontrol_google_client_id';
const DEFAULT_CLIENT='923995580181-vbtua7122vsh385e1bdp7vfuqd49m3q3.apps.googleusercontent.com';
function esc(v){return NGT500.esc(v||'')}
function get(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch(e){return {}}}
function first(v){return String(v||'').split(' ')[0]||''}
function clientId(){return DEFAULT_CLIENT}
function cleanAuthConfig(){localStorage.removeItem(CLIENT_KEY);localStorage.removeItem('terracontrol_drive_token_v1')}
function cloudStatus(){if(!window.NGTCloudBackup)return {};return NGTCloudBackup.status()||{}}
function syncText(){return window.NGTCloudSync?NGTCloudSync.label():'Auto-Sync lädt...'}
function syncIsOn(){return window.NGTCloudSync&&NGTCloudSync.cfg().enabled}
function animalCount(){try{return NGTStore.allAnimals?NGTStore.allAnimals().length:0}catch(e){return 0}}
function loadCloud(cb){if(window.NGTCloudBackup){cb();return;}const c=document.createElement('script');c.src='./v500/cloud-backup.js?v=1.0.2-rc3';c.onload=cb;c.onerror=function(){alert('Cloud-Modul konnte nicht geladen werden.')};document.head.appendChild(c)}
function autoRestoreLatest(){if(localStorage.getItem('terracontrol_rc3_restore_checked'))return;localStorage.setItem('terracontrol_rc3_restore_checked',new Date().toISOString());if(animalCount()>0)return;loadCloud(function(){NGTCloudBackup.listDriveBackups(1).then(function(files){if(!files||!files.length)return;return NGTCloudBackup.downloadDriveFile(files[0].id).then(function(obj){NGTCloudBackup.restoreFromObject(obj);alert('Cloud-Backup wiederhergestellt. TerraControl wird neu geladen.');location.reload()})}).catch(function(e){console.warn('Auto-Restore fehlgeschlagen',e)})})}
function render(){cleanAuthConfig();const p=get();const ok=!!p.email;const st=cloudStatus();const last=st.lastBackupAt?new Date(st.lastBackupAt).toLocaleString('de-DE'):'Noch keine Sicherung';const lastPhoto=st.lastPhotoBackupAt?new Date(st.lastPhotoBackupAt).toLocaleString('de-DE'):'Noch keine Foto-Sicherung';return `<div class="card"><h2>👤 Konto</h2><p class="muted">Google-Anmeldung, Cloud-Sicherung und Gerätewechsel.</p>${ok?`<div class="subcard ok">${p.picture?`<img src="${esc(p.picture)}" style="width:72px;height:72px;border-radius:50%;object-fit:cover;float:right;margin-left:12px">`:''}<b>Angemeldet</b><br>${esc(p.name)}<br>${esc(p.email)}<br><span class="muted">Willkommen ${esc(first(p.given_name||p.name))}</span></div>`:`<div class="subcard"><b>Noch nicht angemeldet</b><br><span class="muted">Melde dich mit Google an.</span></div>`}<div class="subcard"><h3>👤 Anmeldung</h3><div id="googleLoginBox"><button onclick="NGTAccount.googleSignIn()">Mit Google anmelden</button></div><p class="muted">RC3: Nach Google-Anmeldung wird bei leerem Gerät automatisch das neueste Drive-Backup gesucht.</p></div><div class="subcard"><h3>☁️ Cloud</h3><p><b>Status:</b> ${ok?'Konto verbunden':'Konto nicht verbunden'}</p><p><b>Letzte Datensicherung:</b><br>${esc(last)}</p><p><b>Automatische Synchronisierung:</b><br>${esc(syncText())}</p><div class="btnRow"><button onclick="NGTAccount.toggleSync()">${syncIsOn()?'Auto-Sync ausschalten':'Auto-Sync einschalten'}</button><button onclick="NGTAccount.syncNow()">Jetzt synchronisieren</button><button onclick="NGTAccount.cloudDriveBackup()">In Google Drive sichern</button><button onclick="NGTAccount.cloudListDrive()">Backup-Historie</button></div></div><div class="subcard"><h3>📸 Foto-Cloud</h3><p><b>Letzte Foto-Sicherung:</b><br>${esc(lastPhoto)}${st.photoCount?` · ${esc(st.photoCount)} Fotos`:''}</p><div class="btnRow"><button onclick="NGTAccount.photoBackup()">Fotos sichern</button><button onclick="NGTAccount.photoRestore()">Fotos wiederherstellen</button></div></div><div class="subcard"><h3>📦 Lokale Sicherung</h3><div class="btnRow"><button onclick="NGTAccount.cloudBackup()">Datei sichern</button><button onclick="NGTAccount.cloudRestorePick()">Datei wiederherstellen</button></div><input id="cloudRestoreFile" type="file" accept="application/json,.json" style="display:none" onchange="NGTAccount.cloudRestore(this.files[0])"></div><div id="driveBackups"></div><button class="danger" onclick="NGTAccount.clear()">Abmelden / Profil entfernen</button></div>`}
function saveProfile(p){localStorage.setItem(KEY,JSON.stringify(p));localStorage.setItem(GOOGLE_KEY,JSON.stringify(p))}
function save(){NGT500.toast&&NGT500.toast('Profil wird jetzt über Google verwaltet.','warn')}
function saveClientId(){cleanAuthConfig();alert('Google-Konfiguration wurde zurückgesetzt.')}
function clear(){if(confirm('Konto-Daten lokal entfernen?')){localStorage.removeItem(KEY);localStorage.removeItem(GOOGLE_KEY);localStorage.removeItem('terracontrol_rc3_restore_checked');cleanAuthConfig();NGT500.route('account')}}
function decodeJwt(token){try{const part=token.split('.')[1]||'';const b64=part.replace(/-/g,'+').replace(/_/g,'/');const json=decodeURIComponent(atob(b64).split('').map(c=>'%'+('00'+c.charCodeAt(0).toString(16)).slice(-2)).join(''));return JSON.parse(json)}catch(e){return {}}}
function onCredential(res){const d=decodeJwt(res&&res.credential||'');if(!d.email){alert('Google-Anmeldung konnte nicht gelesen werden.');return;}const p={name:d.name||'',displayName:d.name||'',given_name:d.given_name||first(d.name||''),family_name:d.family_name||'',email:d.email||'',picture:d.picture||'',sub:d.sub||'',provider:'google',updatedAt:new Date().toISOString()};saveProfile(p);NGT500.route('account');setTimeout(autoRestoreLatest,800)}
function loadGoogle(cb){if(window.google&&google.accounts&&google.accounts.id){cb();return;}const s=document.createElement('script');s.src='https://accounts.'+'google.com/gsi/client';s.async=true;s.defer=true;s.onload=cb;s.onerror=function(){alert('Google Login konnte nicht geladen werden.')};document.head.appendChild(s)}
function googleSignIn(){cleanAuthConfig();localStorage.removeItem('terracontrol_rc3_restore_checked');loadGoogle(function(){try{google.accounts.id.initialize({client_id:clientId(),callback:onCredential});google.accounts.id.prompt(function(n){if(n&&n.isNotDisplayed&&n.isNotDisplayed()){renderButton()}});renderButton()}catch(e){alert('Google Login Fehler: '+e.message)}})}
function renderButton(){const box=document.getElementById('googleLoginBox');if(!box||!(window.google&&google.accounts&&google.accounts.id))return;box.innerHTML='<div id="googleBtn"></div>';google.accounts.id.renderButton(document.getElementById('googleBtn'),{theme:'outline',size:'large',width:300,text:'signin_with'});}
function cloudBackup(){loadCloud(function(){NGTCloudBackup.download();alert('Cloud-Backup erstellt und als Datei gespeichert.');NGT500.route('account')})}
function cloudDriveBackup(){loadCloud(function(){const box=document.getElementById('driveBackups');if(box)box.innerHTML='<div class="subcard">Google Drive Sicherung läuft...</div>';NGTCloudBackup.uploadToDrive().then(function(){alert('Backup wurde in Google Drive gespeichert.');NGT500.route('account')}).catch(function(e){if(box)box.innerHTML='<div class="subcard danger">'+esc(e.message)+'</div>';alert(e.message)})})}
function photoBackup(){loadCloud(function(){if(!NGTCloudBackup.uploadPhotos){alert('Foto-Cloud lädt noch.');return;}NGTCloudBackup.uploadPhotos().then(function(r){alert('Foto-Sicherung fertig. Gesichert: '+r.uploaded+' Fotos.');NGT500.route('account')}).catch(function(e){alert(e.message)})})}
function photoRestore(){loadCloud(function(){if(!NGTCloudBackup.restorePhotos){alert('Foto-Cloud lädt noch.');return;}if(!confirm('Fotos aus Google Drive wiederherstellen?'))return;NGTCloudBackup.restorePhotos().then(function(r){alert('Fotos wiederhergestellt: '+r.restored);location.reload()}).catch(function(e){alert(e.message)})})}
function cloudListDrive(){loadCloud(function(){const box=document.getElementById('driveBackups');box.innerHTML='<div class="subcard">Backup-Historie wird geladen...</div>';NGTCloudBackup.listDriveBackups(20).then(function(files){box.innerHTML=files.length?'<div class="subcard"><h3>Backup-Historie</h3><p class="muted">'+files.length+' Backups gefunden.</p></div>'+files.map(f=>`<div class="subcard"><b>${esc(f.name)}</b><br>${esc(new Date(f.createdTime).toLocaleString('de-DE'))}<div class="btnRow"><button onclick="NGTAccount.restoreDrive('${esc(f.id)}')">Wiederherstellen</button><button class="danger" onclick="NGTAccount.deleteDrive('${esc(f.id)}')">Löschen</button></div></div>`).join(''):'<div class="subcard">Keine TerraControl-Backups in Google Drive gefunden.</div>'}).catch(function(e){box.innerHTML='<div class="subcard danger">'+esc(e.message)+'</div>'})})}
function cleanupDrive(){loadCloud(function(){NGTCloudBackup.cleanupDriveBackups(20).then(function(r){alert('Aufgeräumt. Gelöscht: '+r.deleted);cloudListDrive()}).catch(function(e){alert(e.message)})})}
function deleteDrive(id){if(!confirm('Dieses Backup aus Google Drive löschen?'))return;loadCloud(function(){NGTCloudBackup.deleteDriveFile(id).then(function(){alert('Backup gelöscht.');cloudListDrive()}).catch(function(e){alert(e.message)})})}
function restoreDrive(id){if(!confirm('Dieses Google-Drive-Backup wiederherstellen? Aktuelle lokale Daten können überschrieben werden.'))return;loadCloud(function(){NGTCloudBackup.downloadDriveFile(id).then(function(obj){NGTCloudBackup.restoreFromObject(obj);alert('Backup wiederhergestellt. App wird neu geladen.');location.reload()}).catch(function(e){alert(e.message)})})}
function cloudRestorePick(){document.getElementById('cloudRestoreFile').click()}
function cloudRestore(file){if(!file)return;if(!confirm('Backup wiederherstellen? Aktuelle lokale Daten können überschrieben werden.'))return;loadCloud(function(){NGTCloudBackup.importFile(file).then(function(){alert('Backup wiederhergestellt. App wird neu geladen.');location.reload()}).catch(function(e){alert('Import fehlgeschlagen: '+e.message)})})}
function toggleSync(){if(!window.NGTCloudSync){alert('Auto-Sync lädt noch.');return;}NGTCloudSync.enable(!NGTCloudSync.cfg().enabled);NGT500.route('account')}
function syncNow(){loadCloud(function(){if(!window.NGTCloudSync){alert('Auto-Sync lädt noch.');return;}NGTCloudSync.setConfig({enabled:true});NGTCloudSync.markDirty('Manuell');NGTCloudSync.syncNow().then(function(){alert('Synchronisiert.');NGT500.route('account')}).catch(function(e){alert(e.message)})})}
function afterRender(){cleanAuthConfig();loadCloud(function(){});if(!window.NGTCloudSync){const y=document.createElement('script');y.src='./v500/cloud-sync.js?v=1.0.2-rc3';document.head.appendChild(y)}setTimeout(function(){loadGoogle(function(){try{google.accounts.id.initialize({client_id:clientId(),callback:onCredential});renderButton()}catch(e){}})},150);if(get().email)setTimeout(autoRestoreLatest,1200)}
window.NGTAccount={save,saveClientId,clear,googleSignIn,cloudBackup,cloudDriveBackup,cloudRestorePick,cloudRestore,cloudListDrive,restoreDrive,deleteDrive,cleanupDrive,toggleSync,syncNow,photoBackup,photoRestore};NGT500.register('account',{render,afterRender});
})();