(function(){
'use strict';
function render(args){const t=args.t||'koenig',edit=args.edit;const list=(NGTStore.data()[t]||[]).map((a,i)=>NGTUI.animalCard({t,i,a})).join('')||'<p class="muted">Noch keine Tiere.</p>';return `<div class="card"><h2>${NGTStore.LABELS[t]}</h2><button onclick="NGTAnimals.openEditor('${t}')">➕ Tier anlegen</button>${edit!==undefined?editor(t,Number(edit)):''}<div>${list}</div></div>`}
function editor(t,i){const a=i!==undefined?NGTStore.animal(t,i):{};const opt=NGTStore.PREY.map(p=>`<option ${p===(a.defaultFeeder||'')?'selected':''}>${p}</option>`).join('');return `<div class="subcard"><h3>${i!==undefined?'Tier bearbeiten':'Tier anlegen'}</h3><input id="edName" placeholder="Name" value="${NGT500.esc(a.name||'')}"><input id="edMorph" placeholder="Morph" value="${NGT500.esc(a.morph||'')}"><input id="edWeight" type="number" placeholder="Gewicht" value="${NGT500.esc(a.weight||'')}"><input id="edOrigin" placeholder="Herkunft" value="${NGT500.esc(a.origin||'')}"><input id="edBirth" type="date" value="${NGT500.esc(a.birth||a.birthDate||'')}"><input id="edBuy" type="number" placeholder="Kaufpreis" value="${NGT500.esc(a.buyPrice||'')}"><select id="edSex"><option ${a.sex==='Unbestimmt'?'selected':''}>Unbestimmt</option><option ${a.sex==='Männlich'?'selected':''}>Männlich</option><option ${a.sex==='Weiblich'?'selected':''}>Weiblich</option></select><select id="edStatus"><option ${a.status==='Bestand'?'selected':''}>Bestand</option><option ${a.status==='Nachzucht'?'selected':''}>Nachzucht</option><option ${a.status==='Archiv'?'selected':''}>Archiv</option></select><select id="edFeeder"><option value="">Kein Standard</option>${opt}</select><textarea id="edNote" placeholder="Notizen">${NGT500.esc(a.note||'')}</textarea><button onclick="NGTAnimals.save('${t}',${i===undefined?'null':i})">💾 Speichern</button></div>`}
function openEditor(t){document.querySelector('.card').insertAdjacentHTML('afterbegin',editor(t));}
function save(t,i){const old=i===null?{}:NGTStore.animal(t,i);const a={...old,name:edName.value.trim()||'Unbenannt',morph:edMorph.value.trim(),weight:edWeight.value,origin:edOrigin.value.trim(),birth:edBirth.value,buyPrice:edBuy.value,sex:edSex.value,status:edStatus.value,defaultFeeder:edFeeder.value,futterStandard:edFeeder.value,standardFeed:edFeeder.value,note:edNote.value.trim()};a.feeds=a.feeds||[];a.sheds=a.sheds||[];a.weights=a.weights||[];a.photos=a.photos||[];if(i===null)NGTStore.addAnimal(t,a);else NGTStore.updateAnimal(t,i,a);NGT500.route('animals',{t});}
function remove(t,i){if(confirm('Tier wirklich löschen?')){NGTStore.deleteAnimal(t,i);NGT500.route('animals',{t})}}
window.NGTAnimals={openEditor,save,remove};NGT500.register('animals',{render});
})();
