(function(){
'use strict';
function render(){
 return `<div class="card"><h2>🤖 KI Assistent</h2><p class="muted">Phase 4.0: Natürlichere Eingaben für Pflege und Futterbestand.</p><textarea id="aiText" placeholder="Medusa hat heute eine 200g Ratte gefressen\nApollo hat gestern verweigert\nMedusa wiegt jetzt 2536 Gramm\nIch habe 25 Ratten 120g gekauft\nIch habe noch 8 Ratten 200g\nMedusa hat sich heute komplett gehäutet"></textarea><button onclick="NGTAssistant.preview()">Analysieren</button><button onclick="NGTAssistant.run()">Ausführen</button><button onclick="NGTAssistant.clearContext()">Kontext löschen</button><div id="aiOut"></div></div>`;
}
function html(s){return NGT500.esc(s||'')}
function show(s){document.getElementById('aiOut').innerHTML=s}
function applyStock(p){const ft=p.feeder;const info=p.stock||NGTAIEngine.stockQty(p.raw);if(!ft||!info.qty)return null;const data=NGTStore.data();let item=data.foodInventory.find(x=>NGTAIEngine.norm(x.name)===NGTAIEngine.norm(ft));if(!item){item={name:ft,qty:0};data.foodInventory.push(item)}if(info.mode==='set')item.qty=Math.max(0,Math.abs(info.qty));else item.qty=Math.max(0,Number(item.qty||0)+info.qty);NGTStore.save();return 'Bestand '+ft+': '+item.qty;}
function applyParsed(p){if(p.intent==='context')return 'Kontext: '+p.animal.a.name;if(p.intent==='stock')return applyStock(p);if(!p.animal)return null;const a=p.animal.a;if(p.intent==='defaultFeeder'){if(!p.feeder)return null;a.defaultFeeder=p.feeder;a.futterStandard=p.feeder;a.standardFeed=p.feeder;NGTStore.save();return a.name+': Standardfutter '+p.feeder;}if(p.intent==='shed'){a.sheds=a.sheds||[];a.sheds.push({date:p.date,complete:true,note:'KI Phase 4.0'});NGTStore.save();return a.name+': Häutung '+p.date;}if(p.intent==='weight'){if(!p.grams)return null;a.weights=a.weights||[];a.weights.push({date:p.date,weight:p.grams,note:'KI Phase 4.0'});a.weight=p.grams;NGTStore.save();return a.name+': Gewicht '+p.date+' '+p.grams+'g';}if(p.intent==='feed'||p.intent==='feed_refused'){const ft=p.feeder||a.defaultFeeder||a.futterStandard||'';const f=NGTStore.parseFeeder(ft);a.feeds=a.feeds||[];a.feeds.push({date:p.date,prey:f.prey,amount:f.amount,accepted:p.intent!=='feed_refused',note:'KI Phase 4.0'});if(f.label)NGTStore.reduceFood(f.label,1);else NGTStore.save();return a.name+': '+p.date+' '+(p.intent==='feed_refused'?'verweigert':'gefressen')+' '+(f.label||'');}return null;}
function rawText(){return document.getElementById('aiText').value}
function parsed(){return (window.NGTAIContext?NGTAIContext.parse:NGTAIEngine.parse)(rawText())}
function recommendationAnswer(){const q=NGTAIEngine.norm(rawText());if(!window.NGTAIRecommendations)return null;if(/empfehl|kritisch|warnung|hinweis|problem|auffaellig|auffällig/.test(q)){return '<div class="subcard ok"><b>KI Empfehlungen</b></div>'+NGTAIRecommendations.render(NGTAIRecommendations.build());}return null;}
function answer(){const r=recommendationAnswer();if(r)return r;const a=window.NGTAIQuery?NGTAIQuery.query(rawText()):null;return a?NGTAIQuery.renderAnswer(a):null}
function preview(){const ans=answer();if(ans){show(ans);return;}const ps=parsed();const ctx=window.NGTAIContext?NGTAIContext.get():{};show(`<div class="subcard">Aktueller Kontext: ${html(ctx.lastAnimal||'-')}</div>`+ps.map(p=>`<div class="subcard"><b>${html(p.intent)}</b><br>Text: ${html(p.raw)}<br>Tier: ${p.animal?html(p.animal.a.name):'nicht erkannt'}<br>Datum: ${html(p.date||'-')}<br>Futter: ${html(p.feeder||'-')}<br>Gewicht: ${html(p.grams||'-')}<br>Bestand: ${p.stock?html(p.stock.mode+' '+p.stock.qty):'-'}</div>`).join(''));}
function run(){const ans=answer();if(ans){show(ans);return;}const ps=parsed();const ok=[];const err=[];ps.forEach(p=>{const r=applyParsed(p);if(r)ok.push(r);else err.push('Nicht gespeichert: '+p.raw)});show((ok.length?`<div class="subcard ok">✅ ${ok.length} Eintrag/Einträge gespeichert.</div>`:'')+ok.map(x=>`<div class="subcard">${html(x)}</div>`).join('')+err.map(x=>`<div class="subcard danger">❌ ${html(x)}</div>`).join(''));}
function clearContext(){if(window.NGTAIContext)NGTAIContext.clear();show('<div class="subcard ok">Kontext gelöscht.</div>')}
window.NGTAssistant={preview,run,clearContext};NGT500.register('assistant',{render});
})();
