(function(){
'use strict';
function render(){return `<div class="card"><h2>🤖 KI Assistent</h2><p class="muted">Speichert Fütterungen, Verweigerungen, Häutungen, Gewichte und Futterbestand direkt in V500.</p><textarea id="aiText" placeholder="Medusa gefressen\nMedusa verweigert\nMedusa gehäutet\nMedusa 2450g\n\nMedusa\n26.06. 200g Ratte\n27.06. 200g Ratte verweigert\n\n200g Ratte +10\n150g Ratte 20"></textarea><button onclick="NGTAssistant.run()">Befehl ausführen</button><div id="aiOut"></div></div>`}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}
function parseDate(s){s=String(s||'');if(norm(s).includes('heute'))return NGT500.today();const m=s.match(/(\d{1,2})[.\-/](\d{1,2})(?:[.\-/](\d{2,4}))?/);if(!m)return '';const y=m[3]?(m[3].length===2?'20'+m[3]:m[3]):String(new Date().getFullYear());return y+'-'+m[2].padStart(2,'0')+'-'+m[1].padStart(2,'0')}
function grams(s){const m=String(s||'').match(/(\d+(?:[,.]\d+)?)\s*(?:g|gramm|gr)\b/i);return m?Number(m[1].replace(',','.')):0}
function result(s){const l=norm(s);if(/verweigert|nicht gefressen|wollte nicht fressen|frisst nicht|abgelehnt|nicht angenommen/.test(l))return false;if(/gefressen|gefuttert|gefüttert|angenommen|hat gefressen|frass|fraß/.test(l))return true;return null}
function feederText(s){const m=String(s||'').match(/(\d+(?:[,.]\d+)?)\s*(?:g|gramm|gr)?\s*(ratte|maus|asf|küken|kueken|heimchen|schabe)/i);if(!m)return '';return Number(m[1].replace(',','.'))+'g '+m[2].replace('kueken','Küken')}
function cleanAnimal(line){return String(line).replace(/\d{1,2}[.\-/]\d{1,2}(?:[.\-/]\d{2,4})?/g,' ').replace(/\d+(?:[,.]\d+)?\s*(?:g|gramm|gr)?\s*(ratte|maus|asf|küken|kueken|heimchen|schabe)?/ig,' ').replace(/heute|hat|wurde|ist|wiegt|gewicht|gehäutet|gehaeutet|häutung|haeutung|gefüttert|gefuttert|gefressen|verweigert|angenommen|abgelehnt|nicht gefressen|wollte nicht fressen|frisst nicht|standardfutter|futter/ig,' ').trim().split(/\s+/)[0]||''}
function findAnimal(txt){const q=norm(txt);if(!q)return null;let hit=NGTStore.findAnimal(q);if(hit)return hit;return NGTStore.allAnimals().find(x=>[x.a.name,x.a.displayId,x.a.uid,x.a.uuid].some(n=>norm(n).includes(q)||q.includes(norm(n))))}
function stockLine(line){const m=String(line).match(/^([+\-])?\s*(\d+(?:[,.]\d+)?)\s*(?:g|gramm|gr)?\s*(ratte|maus|asf|küken|kueken|heimchen|schabe)?\s*([+\-])?\s*(\d+)\s*$/i);if(!m)return null;const pre=m[1]||m[4]||'=';const name=Number(m[2].replace(',','.'))+'g '+(m[3]||'Ratte');const qty=Number(m[5]||0);const data=NGTStore.data();let item=(data.foodInventory||[]).find(x=>norm(x.name)===norm(name));if(!item){item={name,qty:0};data.foodInventory.push(item)}if(pre==='-')item.qty=Math.max(0,Number(item.qty||0)-qty);else if(pre==='+')item.qty=Number(item.qty||0)+qty;else item.qty=qty;NGTStore.save();return `Bestand ${name}: ${item.qty}`}
function setDefault(hit,line){const ft=feederText(line);if(!ft)return null;hit.a.defaultFeeder=ft;hit.a.futterStandard=ft;hit.a.standardFeed=ft;NGTStore.save();return `${hit.a.name}: Standardfutter ${ft}`}
function addFeed(hit,line){const date=parseDate(line)||NGT500.today();const accepted=result(line)!==false;const ft=feederText(line)||hit.a.defaultFeeder||hit.a.futterStandard||'';const p=NGTStore.parseFeeder(ft);hit.a.feeds=hit.a.feeds||[];hit.a.feeds.push({date,prey:p.prey,amount:p.amount,accepted,note:'KI Assistent V500'});hit.a.feeds.sort((a,b)=>String(a.date).localeCompare(String(b.date)));if(p.label)NGTStore.reduceFood(p.label,1);else NGTStore.save();return `${hit.a.name}: ${date} ${accepted?'gefressen':'verweigert'} ${p.label||''}`}
function addShed(hit,line){const date=parseDate(line)||NGT500.today();hit.a.sheds=hit.a.sheds||[];hit.a.sheds.push({date,complete:true,note:'KI Assistent V500'});hit.a.sheds.sort((a,b)=>String(a.date).localeCompare(String(b.date)));NGTStore.save();return `${hit.a.name}: Häutung ${date}`}
function addWeight(hit,line){const g=grams(line);if(!g)return null;const date=parseDate(line)||NGT500.today();hit.a.weights=hit.a.weights||[];hit.a.weights.push({date,weight:g,note:'KI Assistent V500'});hit.a.weights.sort((a,b)=>String(a.date).localeCompare(String(b.date)));hit.a.weight=g;NGTStore.save();return `${hit.a.name}: Gewicht ${date} ${g}g`}
function run(){const lines=document.getElementById('aiText').value.split(/\n|;/).map(x=>x.trim()).filter(Boolean);let current=null,ok=[],err=[];for(const line of lines){const stock=stockLine(line);if(stock){ok.push(stock);continue;}let hit=findAnimal(cleanAnimal(line))||current;const pure=findAnimal(line)&&!parseDate(line)&&!grams(line)&&result(line)===null&&!/gehäutet|gehaeutet|standardfutter/.test(norm(line));if(pure){current=findAnimal(line);continue;}if(!hit){err.push('Tier nicht gefunden: '+line);continue;}current=hit;const l=norm(line);let r=null;if(l.includes('standardfutter'))r=setDefault(hit,line);else if(/gehäutet|gehaeutet/.test(l))r=addShed(hit,line);else if(grams(line)&&!/ratte|maus|asf|küken|kueken|heimchen|schabe|gefressen|verweigert/.test(l))r=addWeight(hit,line);else if(parseDate(line)||result(line)!==null||feederText(line))r=addFeed(hit,line);else err.push('Nicht eindeutig: '+line);if(r)ok.push(r);}document.getElementById('aiOut').innerHTML=(ok.length?`<div class="subcard ok">✅ ${ok.length} Eintrag/Einträge gespeichert.</div>`:'')+ok.map(x=>`<div class="subcard">${NGT500.esc(x)}</div>`).join('')+err.map(x=>`<div class="subcard danger">❌ ${NGT500.esc(x)}</div>`).join('')}
window.NGTAssistant={run};NGT500.register('assistant',{render});
})();
