(function(){
'use strict';
function opt(list,cur){return (list||[]).map(v=>`<option value="${NGT500.esc(v)}" ${String(cur||'')===String(v)?'selected':''}>${NGT500.esc(v)}</option>`).join('')}
function render(){const items=NGTStore.data().foodInventory||[];const firstType=NGTStore.FEEDER_TYPES[0];return `<div class="card"><h2>🥩 Futterverwaltung</h2><div class="subcard"><h3>Futterbestand hinzufügen</h3><select id="foodState"><option>Frost</option><option>Lebend</option></select><select id="foodType" onchange="NGTFood.refreshSizes()">${opt(NGTStore.FEEDER_TYPES,firstType)}</select><select id="foodSize">${opt(NGTStore.FEEDER_SIZES[firstType]||[],(NGTStore.FEEDER_SIZES[firstType]||[])[0])}</select><input id="foodQty" type="number" placeholder="Bestand"><button onclick="NGTFood.save()">💾 Futterbestand speichern</button></div>${items.map((x,i)=>`<div class="subcard"><b>${NGT500.esc(x.label||x.name)}</b><br>Bestand: ${Number(x.qty||0)}<div class="btnRow"><button onclick="NGTFood.edit(${i})">Bestand bearbeiten</button><button class="danger" onclick="NGTFood.del(${i})">Löschen</button></div></div>`).join('')||'<p class="muted">Kein Futterbestand.</p>'}</div>`}
function refreshSizes(){const type=document.getElementById('foodType').value;const size=document.getElementById('foodSize');size.innerHTML=(NGTStore.FEEDER_SIZES[type]||[]).map(v=>`<option value="${NGT500.esc(v)}">${NGT500.esc(v)}</option>`).join('')}
function save(){const state=document.getElementById('foodState').value||'Frost';const type=document.getElementById('foodType').value||'Ratte';const size=document.getElementById('foodSize').value||'';const q=Number(document.getElementById('foodQty').value||0);NGTStore.addFood(NGTStore.feederLabel(state,type,size),q);NGT500.route('food')}
function edit(i){const x=NGTStore.data().foodInventory[i];const q=prompt('Bestand',x.qty);if(q!==null){x.qty=Number(q||0);NGTStore.save();NGT500.route('food')}}
function del(i){if(confirm('Futterbestand löschen?')){NGTStore.data().foodInventory.splice(i,1);NGTStore.save();NGT500.route('food')}}
window.NGTFood={save,edit,del,refreshSizes};NGT500.register('food',{render});
})();