(function(){
'use strict';
let tab='overview',ctx={t:'koenig',i:0};
function current(){return NGTStore.animal(ctx.t,ctx.i)}
function render(args){ctx=args||ctx;tab=args.tab||tab;const a=current();if(!a)return '<div class="card">Tier nicht gefunden.</div>';return `<div class="card"><h2>📁 Tierakte · ${NGT500.esc(a.name)}</h2><div class="subcard"><b>${NGT500.esc(a.name)}</b><br>${NGT500.esc(a.morph||'-')} · ${NGT500.esc(a.sex||'-')} · ${NGT500.esc(a.status||'-')}<br>Standardfutter: ${NGT500.esc(a.defaultFeeder||'-')}<br>UUID: <span class="muted">${NGT500.esc(a.uuid)}</span></div><div class="tabs"><button onclick="NGTProfile.setTab('overview')">Übersicht</button><button onclick="NGTProfile.setTab('timeline')">Timeline</button><button onclick="NGTProfile.setTab('feeds')">Fütterungen</button><button onclick="NGTProfile.setTab('sheds')">Häutungen</button><button onclick="NGTProfile.setTab('weights')">Gewichte</button><button onclick="NGTProfile.setTab('photos')">Fotos</button><button onclick="NGTProfile.setTab('analysis')">Analyse</button><button onclick="NGTProfile.setTab('qr')">QR</button></div><div>${body(a)}</div><button onclick="NGT500.route('animals',{t:'${ctx.t}'})">Zurück</button></div>`}
function body(a){if(tab==='overview')return overview(a);if(tab==='timeline')return NGTUI.list(NGTUI.timeline(a));if(tab==='feeds')return feedForm(a)+NGTUI.list((a.feeds||[]).slice().reverse().map(f=>({d:f.date,txt:`${f.accepted===false?'Verweigert':'Gefressen'} ${f.amount||''}g ${f.prey||''}`})));if(tab==='sheds')return shedForm()+NGTUI.list((a.sheds||[]).slice().reverse().map(s=>({d:s.date,txt:'Häutung'})));if(tab==='weights')return weightForm()+NGTUI.list((a.weights||[]).slice().reverse().map(w=>({d:w.date,txt:w.weight+'g'})));if(tab==='photos')return photos(a);if(tab==='analysis')return analysis(a);if(tab==='qr')return `<div class="qrBox"><div id="profileQr"></div><div>${NGT500.esc(a.uuid)}</div></div>`;return ''}
function overview(a){const p=(a.photos||[])[0],lf=(a.feeds||[]).slice(-1)[0],lw=(a.weights||[]).slice(-1)[0];return `<div class="subcard">${p?`<img class="photo" src="${p.data}">`:''}<br>Kaufwert: ${NGT500.money(a.buyPrice||0)}<br>Marktwert: ${NGT500.money(NGTStore.market(a))}<br>Letzte Fütterung: ${lf?NGT500.esc(lf.date)+' '+(lf.accepted===false?'verweigert':'gefressen'):'-'}<br>Gewicht: ${lw?NGT500.esc(lw.weight)+'g am '+NGT500.esc(lw.date):'-'}<br>Fotos: ${(a.photos||[]).length}<br>Notizen:<br>${NGT500.esc(a.note||'-')}</div>`}
function feedForm(a){return `<div class="subcard"><h3>🍴 Fütterung eintragen</h3><input id="feedDate" type="date" value="${NGT500.today()}"><select id="feedPrey"><option value="${NGT500.esc(a.defaultFeeder||'')}">${NGT500.esc(a.defaultFeeder||'Standardfutter')}</option>${NGTStore.PREY.map(p=>`<option>${p}</option>`).join('')}</select><select id="feedStatus"><option value="ok">Gefressen</option><option value="no">Verweigert</option></select><button onclick="NGTProfile.addFeed()">Fütterung speichern</button></div>`}
function shedForm(){return `<div class="subcard"><h3>🧤 Häutung eintragen</h3><input id="shedDate" type="date" value="${NGT500.today()}"><button onclick="NGTProfile.addShed()">Häutung speichern</button></div>`}
function weightForm(){return `<div class="subcard"><h3>⚖️ Gewicht eintragen</h3><input id="weightDate" type="date" value="${NGT500.today()}"><input id="weightValue" type="number" placeholder="Gewicht in g"><button onclick="NGTProfile.addWeight()">Gewicht speichern</button></div>`}
function photos(a){return `<div class="subcard"><input type="file" accept="image/*" onchange="NGTProfile.addPhoto(this.files[0])"><input id="photoNote" placeholder="Notiz zum Foto"></div>`+(a.photos||[]).map((p,i)=>`<div class="subcard"><img class="photo" src="${p.data}"><b>${NGT500.esc(p.date||'')}</b><br>${NGT500.esc(p.note||'')}<button class="danger" onclick="NGTProfile.deletePhoto(${i})">Foto löschen</button></div>`).join('')}
function analysis(a){const refused=(a.feeds||[]).filter(f=>f.accepted===false).length,accepted=(a.feeds||[]).filter(f=>f.accepted!==false).length,first=(a.weights||[])[0],last=(a.weights||[]).slice(-1)[0];let diff='-';if(first&&last&&first!==last)diff=(Number(last.weight)-Number(first.weight))+'g';return `<div class="subcard">Fütterungen angenommen: ${accepted}<br>Verweigert: ${refused}<br>Häutungen: ${(a.sheds||[]).length}<br>Gewichtsentwicklung: ${diff}<br>Fotos: ${(a.photos||[]).length}</div>`}
function setTab(x){tab=x;NGT500.route('profile',{...ctx,tab})}
function addFeed(){const a=current();const feeder=document.getElementById('feedPrey').value||a.defaultFeeder||'';const p=NGTStore.parseFeeder(feeder);a.feeds=a.feeds||[];a.feeds.push({date:document.getElementById('feedDate').value||NGT500.today(),prey:p.prey,amount:p.amount,accepted:document.getElementById('feedStatus').value!=='no'});if(p.label)NGTStore.reduceFood(p.label,1);else NGTStore.save();setTab('feeds')}
function addShed(){const a=current();a.sheds=a.sheds||[];a.sheds.push({date:document.getElementById('shedDate').value||NGT500.today(),complete:true});NGTStore.save();setTab('sheds')}
function addWeight(){const a=current();const g=Number(document.getElementById('weightValue').value||0);if(!g)return alert('Gewicht fehlt');a.weights=a.weights||[];a.weights.push({date:document.getElementById('weightDate').value||NGT500.today(),weight:g});a.weight=g;NGTStore.save();setTab('weights')}
function addPhoto(file){if(!file)return;const r=new FileReader();r.onload=()=>{const a=current();a.photos=a.photos||[];a.photos.push({id:NGT500.uid(),date:NGT500.today(),note:document.getElementById('photoNote')?.value||'',data:r.result});NGTStore.save();setTab('photos')};r.readAsDataURL(file)}
function deletePhoto(i){if(confirm('Foto löschen?')){current().photos.splice(i,1);NGTStore.save();setTab('photos')}}
function afterRender(){const a=current();if(tab==='qr'&&a&&window.QRCode){document.getElementById('profileQr').innerHTML='';new QRCode(document.getElementById('profileQr'),{text:a.uuid,width:220,height:220})}}
window.NGTProfile={setTab,addPhoto,deletePhoto,addFeed,addShed,addWeight};NGT500.register('profile',{render,afterRender});
})();
