(function(){
'use strict';
let tab='overview',ctx={t:'koenig',i:0};
function current(){return NGTStore.animal(ctx.t,ctx.i)}
function ensure(a){a.health=Array.isArray(a.health)?a.health:[];a.photos=Array.isArray(a.photos)?a.photos:[];a.feeds=Array.isArray(a.feeds)?a.feeds:[];a.sheds=Array.isArray(a.sheds)?a.sheds:[];a.weights=Array.isArray(a.weights)?a.weights:[];}
function latest(list){return (list||[]).slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))[0]||null}
function daysSince(d){const t=Date.parse(d||'');return t?Math.floor((Date.now()-t)/86400000):9999}
function age(birth){const t=Date.parse(birth||'');if(!t)return '-';const y=Math.floor((Date.now()-t)/31557600000);return y>0?y+' Jahre':'< 1 Jahr'}
function healthStatus(a){let score=0;const lf=latest(a.feeds),lw=latest(a.weights),lh=latest(a.health);const recent=(a.feeds||[]).slice().sort((p,q)=>String(q.date||'').localeCompare(String(p.date||''))).slice(0,3);if(recent.length>=2&&recent.slice(0,2).every(f=>f.accepted===false))score+=2;if(lw){const w=(a.weights||[]).slice().sort((p,q)=>String(p.date||'').localeCompare(String(q.date||'')));if(w.length>=2&&Number(w[w.length-1].weight)<Number(w[w.length-2].weight))score+=2}else score+=1;if(daysSince(lf&&lf.date)>=(Number(a.feedIntervalDays||a.feedingInterval||14)+7))score+=1;if(daysSince(lw&&lw.date)>=45)score+=1;if(lh&&String(lh.status||'').toLowerCase()!=='abgeschlossen')score+=1;if(score>=3)return {txt:'Handlungsbedarf',icon:'🔴',cls:'danger'};if(score>=1)return {txt:'Beobachten',icon:'🟡',cls:'ok'};return {txt:'Alles in Ordnung',icon:'🟢',cls:'ok'}}
function passportPayload(a){return JSON.stringify({app:'TerraControl',type:'animal-passport',version:1,animal:{id:a.uuid||a.uid||'',name:a.name||'',morph:a.morph||'',sex:a.sex||'',birth:a.birth||'',origin:a.origin||a.originType||'',father:a.father||a.vater||a.sire||'',mother:a.mother||a.mutter||a.dam||'',defaultFeeder:a.defaultFeeder||'',feedIntervalDays:a.feedIntervalDays||a.feedingInterval||14,weightIntervalDays:30},history:{weights:(a.weights||[]).slice(-10),feeds:(a.feeds||[]).slice(-10),sheds:(a.sheds||[]).slice(-10)}})}
function render(args){ctx=args||ctx;tab=args.tab||tab;const a=current();if(!a)return '<div class="card">Tier nicht gefunden.</div>';ensure(a);const p=(a.photos||[]).find(x=>x.cover)||(a.photos||[])[0];const hs=healthStatus(a);const lw=latest(a.weights);return `<div class="card"><h2>Digitaler Tierpass · ${NGT500.esc(a.name)}</h2>${p?`<img class="photo" src="${p.data}">`:''}<div class="subcard ${hs.cls}"><b>${hs.icon} ${NGT500.esc(hs.txt)}</b><br><b>${NGT500.esc(a.name)}</b><br>${NGT500.esc(a.morph||'-')} · ${NGT500.esc(a.sex||'-')} · ${NGT500.esc(age(a.birth))}<br>Gewicht: ${lw?NGT500.esc(lw.weight)+'g':'-'} · Schlupf: ${NGT500.esc(a.birth||'-')}<br>Standardfutter: ${NGT500.esc(a.defaultFeeder||'-')} · Intervall: ${NGT500.esc(a.feedIntervalDays||a.feedingInterval||14)} Tage<br>UUID: <span class="muted">${NGT500.esc(a.uuid)}</span></div><div class="tabs"><button onclick="NGTProfile.setTab('overview')">Übersicht</button><button onclick="NGTProfile.setTab('life')">Chronik</button><button onclick="NGTProfile.setTab('docs')">Dokumente</button><button onclick="NGTProfile.setTab('feeds')">Fütterungen</button><button onclick="NGTProfile.setTab('sheds')">Häutungen</button><button onclick="NGTProfile.setTab('weights')">Gewichte</button><button onclick="NGTProfile.setTab('photos')">Fotos</button><button onclick="NGTProfile.setTab('health')">Gesundheit</button><button onclick="NGTProfile.setTab('charts')">Diagramme</button><button onclick="NGTProfile.setTab('analysis')">Analyse</button><button onclick="NGTProfile.setTab('qr')">Tierpass QR</button></div><div>${body(a)}</div><button onclick="NGT500.route('animals',{t:'${ctx.t}'})">Zurück</button></div>`}
function body(a){if(tab==='overview')return overview(a);if(tab==='life')return NGTUI.list(NGTUI.timeline(a));if(tab==='docs')return docs(a);if(tab==='feeds')return feedForm(a)+feedList(a);if(tab==='sheds')return shedForm()+shedList(a);if(tab==='weights')return weightForm()+weightList(a);if(tab==='photos')return photos(a);if(tab==='health')return health(a);if(tab==='charts')return charts(a);if(tab==='analysis')return analysis(a);if(tab==='qr')return `<div class="subcard"><h3>Digitaler Tierpass</h3><div class="qrBox"><div id="profileQr"></div></div><p class="muted">QR-Code enthält Stammdaten sowie die letzten 10 Gewichte, Fütterungen und Häutungen.</p><textarea readonly>${NGT500.esc(passportPayload(a))}</textarea></div>`;return ''}
function overview(a){const lf=latest(a.feeds),lw=latest(a.weights),lh=latest(a.health);return `<div class="grid"><div class="stat">Fotos<b>${(a.photos||[]).length}</b></div><div class="stat">Fütterungen<b>${(a.feeds||[]).length}</b></div><div class="stat">Gewichte<b>${(a.weights||[]).length}</b></div><div class="stat">Gesundheit<b>${(a.health||[]).length}</b></div></div><div class="subcard">Kaufwert: ${NGT500.money(a.buyPrice||0)}<br>Marktwert: ${NGT500.money(NGTStore.market(a))}<br>Letzte Fütterung: ${lf?NGT500.esc(lf.date)+' '+(lf.accepted===false?'verweigert':'gefressen'):'-'}<br>Gewicht: ${lw?NGT500.esc(lw.weight)+'g am '+NGT500.esc(lw.date):'-'}<br>Letzter Gesundheits-Eintrag: ${lh?NGT500.esc(lh.date)+' '+NGT500.esc(lh.title||lh.type):'-'}<br>Vater: ${NGT500.esc(a.father||a.vater||a.sire||'-')}<br>Mutter: ${NGT500.esc(a.mother||a.mutter||a.dam||'-')}<br>Notizen:<br>${NGT500.esc(a.note||'-')}</div>`}
function docs(a){const uid=encodeURIComponent(a.uuid||a.uid||'');return `<div class="subcard"><h3>Dokumentencenter</h3><div class="btnRow"><button onclick="location.href='./abgabe.html?id=${uid}'">Abgabenachweis / PDF</button><button onclick="NGTProfile.setTab('qr')">Digitaler Tierpass QR</button></div><p class="muted">Später kommen hier Herkunftsnachweise, CITES/Artenschutz-Dokumente und Verkaufsunterlagen hinzu.</p></div>`}
function feedForm(a){return `<div class="subcard"><h3>Fütterung eintragen</h3><input id="feedDate" type="date" value="${NGT500.today()}"><select id="feedPrey"><option value="${NGT500.esc(a.defaultFeeder||'')}">${NGT500.esc(a.defaultFeeder||'Standardfutter')}</option>${NGTStore.PREY.map(p=>`<option>${p}</option>`).join('')}</select><select id="feedStatus"><option value="ok">Gefressen</option><option value="no">Verweigert</option></select><button onclick="NGTProfile.addFeed()">Fütterung speichern</button></div>`}
function shedForm(){return `<div class="subcard"><h3>Häutung eintragen</h3><input id="shedDate" type="date" value="${NGT500.today()}"><button onclick="NGTProfile.addShed()">Häutung speichern</button></div>`}
function weightForm(){return `<div class="subcard"><h3>Gewicht eintragen</h3><input id="weightDate" type="date" value="${NGT500.today()}"><input id="weightValue" type="number" placeholder="Gewicht in g"><button onclick="NGTProfile.addWeight()">Gewicht speichern</button></div>`}
function row(d,txt,del){return `<div class="listLine"><b>${NGT500.esc(d||'-')}</b> ${NGT500.esc(txt||'')}<button class="danger" onclick="${del}">Löschen</button></div>`}
function feedList(a){return (a.feeds||[]).map((f,i)=>({f,i})).reverse().map(x=>row(x.f.date,`${x.f.accepted===false?'Verweigert':'Gefressen'} ${x.f.amount||''}g ${x.f.prey||''}`,`NGTProfile.deleteEntry('feeds',${x.i})`)).join('')||'<p class="muted">Keine Fütterungen.</p>'}
function shedList(a){return (a.sheds||[]).map((s,i)=>({s,i})).reverse().map(x=>row(x.s.date,'Häutung',`NGTProfile.deleteEntry('sheds',${x.i})`)).join('')||'<p class="muted">Keine Häutungen.</p>'}
function weightList(a){return (a.weights||[]).map((w,i)=>({w,i})).reverse().map(x=>row(x.w.date,x.w.weight+'g',`NGTProfile.deleteEntry('weights',${x.i})`)).join('')||'<p class="muted">Keine Gewichte.</p>'}
function photos(a){return `<div class="subcard"><h3>Foto hinzufügen</h3><input type="file" accept="image/*" onchange="NGTProfile.addPhoto(this.files[0])"><select id="photoType"><option>Portrait</option><option>Terrarium</option><option>Häutung</option><option>Fütterung</option><option>Nachwuchs</option><option>Gesundheit</option><option>Sonstige</option></select><input id="photoNote" placeholder="Notiz zum Foto"><p class="muted">Das erste Foto wird automatisch Titelbild. Über „Als Titelbild“ kannst du es ändern.</p></div>`+(a.photos||[]).map((p,i)=>`<div class="subcard"><img class="photo" src="${p.data}"><b>${NGT500.esc(p.date||'')}</b> · ${NGT500.esc(p.type||'Sonstige')} ${p.cover?'· Titelbild':''}<br>${NGT500.esc(p.note||'')}<div class="btnRow"><button onclick="NGTProfile.setCover(${i})">Als Titelbild</button><button class="danger" onclick="NGTProfile.deletePhoto(${i})">Foto löschen</button></div></div>`).join('')}
function health(a){return healthForm()+((a.health||[]).map((h,i)=>({h,i})).reverse().map(x=>`<div class="subcard"><b>${NGT500.esc(x.h.date||'-')} · ${NGT500.esc(x.h.type||'Gesundheit')}</b><br>${NGT500.esc(x.h.title||'')}<br>${NGT500.esc(x.h.medication||'')} ${NGT500.esc(x.h.dose||'')} ${NGT500.esc(x.h.duration||'')}<br>Status: ${NGT500.esc(x.h.status||'-')}<br>${NGT500.esc(x.h.note||'')}<button class="danger" onclick="NGTProfile.deleteEntry('health',${x.i})">Eintrag löschen</button></div>`).join('')||'<p class="muted">Keine Gesundheitsdaten.</p>')}
function healthForm(){return `<div class="subcard"><h3>Gesundheits-Eintrag</h3><input id="healthDate" type="date" value="${NGT500.today()}"><select id="healthType"><option>Tierarzt</option><option>Behandlung</option><option>Medikament</option><option>Diagnose</option><option>Kontrolle</option><option>Kotprobe</option><option>Parasitenbehandlung</option><option>OP</option><option>Verletzung</option><option>Quarantäne</option><option>Notiz</option></select><input id="healthTitle" placeholder="Titel / Diagnose"><input id="healthMedication" placeholder="Medikament"><input id="healthDose" placeholder="Dosierung"><input id="healthDuration" placeholder="Dauer"><select id="healthStatus"><option>offen</option><option>laufend</option><option>abgeschlossen</option></select><textarea id="healthNote" placeholder="Notizen"></textarea><button onclick="NGTProfile.addHealth()">Gesundheit speichern</button></div>`}
function charts(a){return `<div class="subcard"><h3>Gewicht</h3>${barChart((a.weights||[]).map(w=>({label:w.date,value:Number(w.weight||0)})))}</div><div class="subcard"><h3>Fütterungen</h3>${barChart((a.feeds||[]).map(f=>({label:f.date,value:f.accepted===false?0:1})),true)}</div>`}
function barChart(data,binary){if(!data.length)return '<p class="muted">Keine Daten.</p>';const max=Math.max(...data.map(x=>x.value),1);return data.slice(-18).map(x=>`<div style="margin:8px 0"><small>${NGT500.esc(x.label)}</small><div style="height:14px;background:#0f1a25;border:1px solid var(--line);border-radius:999px;overflow:hidden"><div style="height:100%;width:${Math.max(5,(x.value/max)*100)}%;background:var(--accent)"></div></div><small>${binary?(x.value?'ja':'nein'):NGT500.esc(x.value+'g')}</small></div>`).join('')}
function analysis(a){const refused=(a.feeds||[]).filter(f=>f.accepted===false).length,accepted=(a.feeds||[]).filter(f=>f.accepted!==false).length,first=(a.weights||[])[0],last=(a.weights||[]).slice(-1)[0];let diff='-';if(first&&last&&first!==last)diff=(Number(last.weight)-Number(first.weight))+'g';return `<div class="subcard">Fütterungen angenommen: ${accepted}<br>Verweigert: ${refused}<br>Häutungen: ${(a.sheds||[]).length}<br>Gesundheits-Einträge: ${(a.health||[]).length}<br>Gewichtsentwicklung: ${diff}<br>Fotos: ${(a.photos||[]).length}</div>`}
function setTab(x){tab=x;NGT500.route('profile',{...ctx,tab})}
function addFeed(){const a=current();const feeder=document.getElementById('feedPrey').value||a.defaultFeeder||'';const p=NGTStore.parseFeeder(feeder);a.feeds=a.feeds||[];a.feeds.push({date:document.getElementById('feedDate').value||NGT500.today(),prey:p.prey,amount:p.amount,accepted:document.getElementById('feedStatus').value!=='no'});if(p.label)NGTStore.reduceFood(p.label,1);else NGTStore.save();setTab('feeds')}
function addShed(){const a=current();a.sheds=a.sheds||[];a.sheds.push({date:document.getElementById('shedDate').value||NGT500.today(),complete:true});NGTStore.save();setTab('sheds')}
function addWeight(){const a=current();const g=Number(document.getElementById('weightValue').value||0);if(!g)return alert('Gewicht fehlt');a.weights=a.weights||[];a.weights.push({date:document.getElementById('weightDate').value||NGT500.today(),weight:g});a.weight=g;NGTStore.save();setTab('weights')}
function addHealth(){const a=current();a.health=a.health||[];a.health.push({id:NGT500.uid(),date:healthDate.value||NGT500.today(),type:healthType.value,title:healthTitle.value,medication:healthMedication.value,dose:healthDose.value,duration:healthDuration.value,status:healthStatus.value,note:healthNote.value});NGTStore.save();setTab('health')}
function deleteEntry(kind,i){if(!confirm('Eintrag löschen?'))return;const a=current();a[kind].splice(i,1);if(kind==='weights'){const last=(a.weights||[]).slice(-1)[0];a.weight=last?last.weight:'';}NGTStore.save();setTab(tab)}
function compressPhoto(file){return new Promise((resolve,reject)=>{const img=new Image();const r=new FileReader();r.onerror=reject;r.onload=()=>{img.onload=()=>{const max=900;let w=img.width,h=img.height;if(w>h&&w>max){h=Math.round(h*max/w);w=max}else if(h>=w&&h>max){w=Math.round(w*max/h);h=max}const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',0.72));};img.onerror=reject;img.src=r.result;};r.readAsDataURL(file);});}
async function addPhoto(file){if(!file)return;try{const a=current();a.photos=a.photos||[];const data=await compressPhoto(file);a.photos.push({id:NGT500.uid(),date:NGT500.today(),type:document.getElementById('photoType')?.value||'Sonstige',note:document.getElementById('photoNote')?.value||'',cover:a.photos.length===0,data});NGTStore.save();setTab('photos')}catch(e){alert('Foto konnte nicht dauerhaft gespeichert werden. Bitte kleineres Foto wählen oder Backup/Drive-Speicher aktivieren.')}}
function setCover(i){const a=current();(a.photos||[]).forEach((p,n)=>p.cover=n===i);NGTStore.save();setTab('photos')}
function deletePhoto(i){if(confirm('Foto löschen?')){current().photos.splice(i,1);NGTStore.save();setTab('photos')}}
function afterRender(){const a=current();if(tab==='qr'&&a&&window.QRCode){const box=document.getElementById('profileQr');box.innerHTML='';new QRCode(box,{text:passportPayload(a),width:220,height:220,correctLevel:QRCode.CorrectLevel.L})}}
window.NGTProfile={setTab,addPhoto,setCover,deletePhoto,addFeed,addShed,addWeight,addHealth,deleteEntry};NGT500.register('profile',{render,afterRender});
})();