(function(){
'use strict';
const KEY='terracontrol_settings_v1';
const SELLER_KEY='ngt_seller_profile_v1';
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
function seller(){try{return JSON.parse(localStorage.getItem(SELLER_KEY)||'{}')}catch(e){return {}}}
function saveObj(k,o){localStorage.setItem(k,JSON.stringify(o));}
function render(){const s=load(),v=s.defaults||{},p=seller();return `<div class="card"><h2>Einstellungen</h2><p class="muted">TerraControl 1.0 · zentrale App-Einstellungen</p><div class="subcard"><h3>Verkäuferdaten</h3><input id="setSellerName" placeholder="Name" value="${NGT500.esc(p.name||'')}"><input id="setSellerStreet" placeholder="Straße / Hausnummer" value="${NGT500.esc(p.street||p.address||'')}"><input id="setSellerCity" placeholder="PLZ / Ort" value="${NGT500.esc(p.city||'')}"><input id="setSellerPhone" placeholder="Telefon" value="${NGT500.esc(p.phone||'')}"><input id="setSellerMail" placeholder="E-Mail" value="${NGT500.esc(p.email||p.mail||'')}"><p class="muted">Diese Daten werden für Abgabenachweise verwendet.</p></div><div class="subcard"><h3>Standardwerte</h3><input id="setFeedBaby" type="number" min="1" placeholder="Fütterungsintervall Jungtier" value="${NGT500.esc(v.feedBaby||7)}"><input id="setFeedSubadult" type="number" min="1" placeholder="Fütterungsintervall Subadult" value="${NGT500.esc(v.feedSubadult||10)}"><input id="setFeedAdult" type="number" min="1" placeholder="Fütterungsintervall Adult" value="${NGT500.esc(v.feedAdult||14)}"><input id="setWeightDays" type="number" min="1" placeholder="Gewichtsintervall" value="${NGT500.esc(v.weightDays||30)}"><p class="muted">Gewichtsintervall bleibt standardmäßig 30 Tage. Einzeltiere können eigene Fütterungsintervalle haben.</p></div><div class="subcard"><h3>Cloud & Backup</h3><p>Google Drive Synchronisierung: <b>vorbereitet</b></p><p class="muted">Cloud-Login wird in Version 1.1 ergänzt. Bis dahin bitte regelmäßig lokale Backups exportieren.</p><button onclick="NGT500.route('backup')">Backup öffnen</button></div><div class="subcard"><h3>Release</h3>App: <b>TerraControl</b><br>Version: <b>1.0</b><br>Status: <b>Release Candidate</b></div><button onclick="NGTSettings.save()">Einstellungen speichern</button></div>`}
function save(){const p={name:setSellerName.value.trim(),street:setSellerStreet.value.trim(),address:setSellerStreet.value.trim(),city:setSellerCity.value.trim(),phone:setSellerPhone.value.trim(),email:setSellerMail.value.trim(),mail:setSellerMail.value.trim()};saveObj(SELLER_KEY,p);const s=load();s.defaults={feedBaby:Number(setFeedBaby.value||7),feedSubadult:Number(setFeedSubadult.value||10),feedAdult:Number(setFeedAdult.value||14),weightDays:Number(setWeightDays.value||30)};saveObj(KEY,s);alert('Einstellungen gespeichert.');}
window.NGTSettings={save};NGT500.register('settings',{render});
})();