(function(){
'use strict';
const KEY='spd_v53';
const TYPES=['koenig','boas','geckos','spinnen'];
const LABELS={koenig:'🐍 Königspythons',boas:'🐍 Boas',geckos:'🦎 Leopardgeckos',spinnen:'🕷 Vogelspinnen'};
const PREY=['Ratte 10g','Ratte 20g','Ratte 30g','Ratte 50g','Ratte 70g','Ratte 90g','Ratte 120g','Ratte 150g','Ratte 200g','Ratte 250g','Maus 10g','Maus 20g','Maus 30g','Maus 50g','ASF 20g','ASF 30g','ASF 50g','Küken','Heimchen klein','Heimchen mittel','Heimchen groß','Schabe klein','Schabe mittel','Schabe groß'];
let db=load();let currentType='koenig';let editType=null;let editIndex=null;
function uid(){return 'ngt-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)}
function base(){return {koenig:[],boas:[],geckos:[],spinnen:[],clutches:[],sales:[],archive:[],foodInventory:[],settings:{}}}
function load(){try{const d=JSON.parse(localStorage.getItem(KEY)||'null')||base();return normalize(d);}catch(e){return base();}}
function save(){normalize(db);localStorage.setItem(KEY,JSON.stringify(db));render();}
function normalize(d){TYPES.forEach(t=>{if(!Array.isArray(d[t]))d[t]=[];d[t].forEach((a,i)=>{a.uuid=a.uuid||a.uid||uid();a.uid=a.uid||a.uuid;a.type=a.type||t;a.name=a.name||a.displayId||(`${t}-${i+1}`);a.status=a.status||'Bestand';a.feeds=Array.isArray(a.feeds)?a.feeds:[];a.sheds=Array.isArray(a.sheds)?a.sheds:[];a.weights=Array.isArray(a.weights)?a.weights:[];a.feeds.sort(byDate);a.sheds.sort(byDate);a.weights.sort(byDate);a.defaultFeeder=a.defaultFeeder||a.futterStandard||a.standardFeed||'';});});['clutches','sales','archive','foodInventory'].forEach(k=>{if(!Array.isArray(d[k]))d[k]=[]});return d;}
function byDate(a,b){return String(a.date||'').localeCompare(String(b.date||''));}
function $(id){return document.getElementById(id)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(n){return Number(n||0).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})+' €'}
function allAnimals(){return TYPES.flatMap(t=>(db[t]||[]).map((a,i)=>({t,i,a})));}
function market(a){const buy=Number(a.buyPrice||0);const txt=(a.morph||'').toLowerCase();let v=buy||80;if(txt.includes('ultramel'))v+=260;if(txt.includes('clown'))v+=300;if(txt.includes('pied'))v+=250;if(txt.includes('desert ghost'))v+=350;if(txt.includes('leopard'))v+=60;if(txt.includes('pastel'))v+=40;if(a.sex==='Weiblich')v*=1.15;return Math.round(v);} 
function setPage(id){document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active');closeMenu();currentType=id;render();}
function openMenu(){ $('drawer').classList.add('open');$('overlay').classList.add('show') }
function closeMenu(){ $('drawer').classList.remove('open');$('overlay').classList.remove('show') }
function stats(){const animals=allAnimals().filter(x=>x.a.status!=='Archiv');const buy=animals.reduce((s,x)=>s+Number(x.a.buyPrice||0),0);const mv=animals.reduce((s,x)=>s+market(x.a),0);return {count:animals.length,buy,mv,archive:db.archive.length,nz:db.clutches.length,sales:db.sales.length};}
function renderHome(){const s=stats();$('overview').innerHTML=`<div class="grid"><div class="stat">Gesamtbestand<b>${s.count}</b></div><div class="stat">Kaufwert<b>${money(s.buy)}</b></div><div class="stat">Marktwert geschätzt<b>${money(s.mv)}</b></div><div class="stat">Differenz<b>${money(s.mv-s.buy)}</b></div></div><p class="muted">Marktwert ist eine konservative Schätzung aus Morph, Geschlecht und Einkaufspreis.</p>`;renderFoodOverview();renderRecent();}
function renderFoodOverview(){const items=(db.foodInventory||[]).filter(x=>Number(x.qty)>0);$('foodOverview').innerHTML=items.length?items.map(x=>`<div class="subcard"><b>${esc(x.name)}</b><br>Bestand: ${Number(x.qty||0)}</div>`).join(''):'<p class="muted">Kein Futterbestand eingetragen.</p>';}
function renderRecent(){let rows=[];allAnimals().forEach(({a})=>{(a.feeds||[]).forEach(f=>rows.push({d:f.date,t:`${a.name}: ${f.accepted===false?'verweigert':'gefressen'} ${f.amount?f.amount+'g ':''}${f.prey||''}`}));(a.sheds||[]).forEach(s=>rows.push({d:s.date,t:`${a.name}: Häutung`}));(a.weights||[]).forEach(w=>rows.push({d:w.date,t:`${a.name}: ${w.weight}g`}));});rows.sort((a,b)=>String(b.d).localeCompare(String(a.d)));$('recent').innerHTML=rows.slice(0,10).map(r=>`<div class="listLine"><b>${esc(r.d||'-')}</b> ${esc(r.t)}</div>`).join('')||'<p class="muted">Noch keine Aktivitäten.</p>';}
function renderAnimals(t){const box=$(t+'List');if(!box)return;box.innerHTML=(db[t]||[]).map((a,i)=>animalCard(t,a,i)).join('')||'<p class="muted">Noch keine Tiere.</p>';}
function animalCard(t,a,i){const lastFeed=(a.feeds||[]).slice(-1)[0];const lastWeight=(a.weights||[]).slice(-1)[0];return `<div class="animal"><h3>${esc(a.name)}</h3><span class="pill">${esc(a.morph||'-')}</span><span class="pill">${esc(a.sex||'-')}</span><span class="pill">${esc(a.status||'-')}</span><br>${a.defaultFeeder?`🍽️ Standard: <b>${esc(a.defaultFeeder)}</b><br>`:''}💵 Kauf: ${money(a.buyPrice||0)} · Markt: ${money(market(a))}<br>${lastFeed?`🍴 Letzte Fütterung: ${esc(lastFeed.date)} ${lastFeed.accepted===false?'verweigert':'gefressen'}<br>`:''}${lastWeight?`⚖️ Gewicht: ${esc(lastWeight.weight)}g (${esc(lastWeight.date)})<br>`:''}<div class="btnRow"><button onclick="NGT.edit('${t}',${i})">✏️ Bearbeiten</button><button onclick="NGT.openLog('${t}',${i})">📋 Verlauf</button><button onclick="NGT.qr('${t}',${i})">📱 QR-Code</button><button class="danger" onclick="NGT.remove('${t}',${i})">🗑️ Löschen</button></div></div>`}
function renderFoodPage(){const box=$('foodList');box.innerHTML=(db.foodInventory||[]).map((x,i)=>`<div class="subcard"><b>${esc(x.name)}</b><br>Bestand: ${Number(x.qty||0)}<div class="btnRow"><button onclick="NGT.foodEdit(${i})">✏️ Bearbeiten</button><button class="danger" onclick="NGT.foodDelete(${i})">🗑️ Löschen</button></div></div>`).join('')||'<p class="muted">Kein Futterbestand.</p>';}
function render(){normalize(db);renderHome();TYPES.forEach(renderAnimals);renderFoodPage();}
function addAnimal(t){editType=t;editIndex=null;openEditor({type:t,status:'Bestand'});}
function edit(t,i){editType=t;editIndex=i;openEditor(db[t][i]);}
function openEditor(a){$('modalTitle').textContent=editIndex===null?'Tier anlegen':'Tier bearbeiten';$('ae_name').value=a.name||'';$('ae_morph').value=a.morph||'';$('ae_weight').value=a.weight||'';$('ae_origin').value=a.origin||'';$('ae_birth').value=a.birth||a.birthDate||'';$('ae_buy').value=a.buyPrice||'';$('ae_price').value=a.price||'';$('ae_sex').value=a.sex||'Unbestimmt';$('ae_status').value=a.status||'Bestand';$('ae_feeder').innerHTML='<option value="">Kein Standard</option>'+PREY.map(p=>`<option ${p===(a.defaultFeeder||'')?'selected':''}>${p}</option>`).join('');$('ae_note').value=a.note||'';$('modal').classList.add('show');}
function closeEditor(){$('modal').classList.remove('show')}
function saveEditor(){const a={...(editIndex===null?{}:db[editType][editIndex])};a.uuid=a.uuid||uid();a.uid=a.uid||a.uuid;a.type=editType;a.name=$('ae_name').value.trim()||'Unbenannt';a.morph=$('ae_morph').value.trim();a.weight=$('ae_weight').value;a.origin=$('ae_origin').value.trim();a.birth=$('ae_birth').value;a.buyPrice=$('ae_buy').value;a.price=$('ae_price').value;a.sex=$('ae_sex').value;a.status=$('ae_status').value;a.defaultFeeder=$('ae_feeder').value;a.futterStandard=a.defaultFeeder;a.standardFeed=a.defaultFeeder;a.note=$('ae_note').value.trim();a.feeds=a.feeds||[];a.sheds=a.sheds||[];a.weights=a.weights||[];if(editIndex===null)db[editType].push(a);else db[editType][editIndex]=a;closeEditor();save();}
function remove(t,i){if(confirm('Tier wirklich löschen?')){db[t].splice(i,1);save();}}
function openLog(t,i){const a=db[t][i];$('logTitle').textContent=a.name+' Verlauf';$('logAnimal').textContent=t+'|'+i;renderLog(t,i);$('logModal').classList.add('show');}
function closeLog(){$('logModal').classList.remove('show')}
function renderLog(t,i){const a=db[t][i];let rows=[];(a.feeds||[]).forEach(f=>rows.push({d:f.date,txt:`🍴 ${f.accepted===false?'Verweigert':'Gefressen'} ${f.amount?f.amount+'g ':''}${f.prey||''}`}));(a.sheds||[]).forEach(s=>rows.push({d:s.date,txt:'🧤 Häutung'}));(a.weights||[]).forEach(w=>rows.push({d:w.date,txt:`⚖️ ${w.weight}g`}));rows.sort((x,y)=>String(y.d).localeCompare(String(x.d)));$('logList').innerHTML=rows.map(r=>`<div class="listLine"><b>${esc(r.d)}</b> ${esc(r.txt)}</div>`).join('')||'<p class="muted">Noch keine Einträge.</p>';}
function logTarget(){const [t,i]=$('logAnimal').textContent.split('|');return {t,i:Number(i),a:db[t][Number(i)]}}
function addFeed(){const {t,i,a}=logTarget();const date=$('feedDate').value||new Date().toISOString().slice(0,10);const feeder=$('feedPrey').value||a.defaultFeeder||'';const accepted=$('feedStatus').value!=='verweigert';const p=parseFeeder(feeder);a.feeds.push({date,prey:p.prey,amount:p.amount,accepted});a.feeds.sort(byDate);reduceFood(`${p.amount}g ${p.prey}`,1);save();openLog(t,i)}
function addShed(){const {t,i,a}=logTarget();const date=$('shedDate').value||new Date().toISOString().slice(0,10);a.sheds.push({date,complete:true});a.sheds.sort(byDate);save();openLog(t,i)}
function addWeight(){const {t,i,a}=logTarget();const date=$('weightDate').value||new Date().toISOString().slice(0,10);const weight=Number($('weightValue').value||0);if(!weight)return alert('Gewicht fehlt');a.weights.push({date,weight});a.weights.sort(byDate);a.weight=weight;save();openLog(t,i)}
function parseFeeder(s){const m=String(s||'').match(/(Ratte|Maus|ASF|Küken|Heimchen|Schabe)\s*(\d+)?g?/i)||String(s||'').match(/(\d+)\s*g\s*(Ratte|Maus|ASF|Küken|Heimchen|Schabe)/i);if(!m)return {prey:'Ratte',amount:0};if(isNaN(Number(m[1])))return {prey:m[1],amount:Number(m[2]||0)};return {prey:m[2],amount:Number(m[1]||0)};}
function reduceFood(name,n){const item=(db.foodInventory||[]).find(x=>x.name===name);if(item)item.qty=Math.max(0,Number(item.qty||0)-n);}
function foodAdd(){const name=$('foodName').value.trim();const qty=Number($('foodQty').value||0);if(!name)return;const item=db.foodInventory.find(x=>x.name===name);if(item)item.qty=qty;else db.foodInventory.push({name,qty});$('foodName').value='';$('foodQty').value='';save();}
function foodEdit(i){const x=db.foodInventory[i];const q=prompt('Bestand',x.qty);if(q!==null){x.qty=Number(q||0);save();}}
function foodDelete(i){if(confirm('Futterbestand löschen?')){db.foodInventory.splice(i,1);save();}}
function qr(t,i){const a=db[t][i];$('qrTitle').textContent=a.name+' QR-Code';$('qrCode').innerHTML='';$('qrText').textContent=a.uuid;if(window.QRCode)new QRCode($('qrCode'),{text:a.uuid,width:220,height:220});else $('qrCode').textContent=a.uuid;$('qrModal').classList.add('show');}
function findQr(){const v=$('qrSearchId').value.trim();const hit=allAnimals().find(x=>x.a.uuid===v||x.a.uid===v||x.a.name===v);$('qrSearchResult').innerHTML=hit?animalCard(hit.t,hit.a,hit.i):'<p class="muted">Tier nicht gefunden.</p>';}
function search(){const q=$('globalSearch').value.toLowerCase();const rows=allAnimals().filter(x=>JSON.stringify(x.a).toLowerCase().includes(q));$('searchResults').style.display=q?'block':'none';$('searchResults').innerHTML=rows.map(x=>animalCard(x.t,x.a,x.i)).join('')||'Keine Treffer';}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ng-terrarium-backup.json';a.click();}
function importData(file){const r=new FileReader();r.onload=()=>{try{db=normalize(JSON.parse(r.result));save();alert('Import erfolgreich');}catch(e){alert('Import fehlgeschlagen')}};r.readAsText(file);}
window.NGT={setPage,openMenu,closeMenu,addAnimal,edit,remove,saveEditor,closeEditor,openLog,closeLog,addFeed,addShed,addWeight,foodAdd,foodEdit,foodDelete,qr,findQr,search,exportData,importData};
document.addEventListener('DOMContentLoaded',()=>{PREY.forEach(p=>{$('feedPrey').insertAdjacentHTML('beforeend',`<option>${p}</option>`)});render();});
})();