(function(){
'use strict';
const KEY='spd_v53';
const TYPES=['koenig','boas','geckos','spinnen'];
const PREY=['Ratte 10g','Ratte 20g','Ratte 30g','Ratte 50g','Ratte 70g','Ratte 90g','Ratte 120g','Ratte 150g','Ratte 200g','Ratte 250g','Maus 10g','Maus 20g','Maus 30g','Maus 50g','ASF 20g','ASF 30g','ASF 50g','Küken','Heimchen klein','Heimchen mittel','Heimchen groß','Schabe klein','Schabe mittel','Schabe groß'];
let db=load();let currentType='koenig';let editType=null;let editIndex=null;let profileType=null;let profileIndex=null;let activeTab='overview';
function uid(){return 'ngt-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)}
function base(){return {koenig:[],boas:[],geckos:[],spinnen:[],clutches:[],sales:[],archive:[],foodInventory:[],settings:{}}}
function load(){try{return normalize(JSON.parse(localStorage.getItem(KEY)||'null')||base());}catch(e){return base();}}
function save(){normalize(db);localStorage.setItem(KEY,JSON.stringify(db));render();if(profileType!==null)renderProfile();}
function normalize(d){TYPES.forEach(t=>{if(!Array.isArray(d[t]))d[t]=[];d[t].forEach((a,i)=>{a.uuid=a.uuid||a.uid||uid();a.uid=a.uid||a.uuid;a.type=a.type||t;a.name=a.name||a.displayId||(`${t}-${i+1}`);a.status=a.status||'Bestand';a.feeds=Array.isArray(a.feeds)?a.feeds:[];a.sheds=Array.isArray(a.sheds)?a.sheds:[];a.weights=Array.isArray(a.weights)?a.weights:[];a.photos=Array.isArray(a.photos)?a.photos:[];a.feeds.sort(byDate);a.sheds.sort(byDate);a.weights.sort(byDate);a.photos.sort((x,y)=>String(y.date||'').localeCompare(String(x.date||'')));a.defaultFeeder=a.defaultFeeder||a.futterStandard||a.standardFeed||'';});});['clutches','sales','archive','foodInventory'].forEach(k=>{if(!Array.isArray(d[k]))d[k]=[]});return d;}
function byDate(a,b){return String(a.date||'').localeCompare(String(b.date||''));}
function $(id){return document.getElementById(id)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(n){return Number(n||0).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})+' €'}
function allAnimals(){return TYPES.flatMap(t=>(db[t]||[]).map((a,i)=>({t,i,a})));}
function nameOf(a){return a.name||a.displayId||a.uid||'Tier'}
function market(a){const buy=Number(a.buyPrice||0);const txt=(a.morph||'').toLowerCase();let v=buy||80;if(txt.includes('ultramel'))v+=260;if(txt.includes('clown'))v+=300;if(txt.includes('pied'))v+=250;if(txt.includes('desert ghost'))v+=350;if(txt.includes('leopard'))v+=60;if(txt.includes('pastel'))v+=40;if(a.sex==='Weiblich')v*=1.15;return Math.round(v);} 
function setPage(id){document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active');closeMenu();currentType=id;render();}
function openMenu(){ $('drawer').classList.add('open');$('overlay').classList.add('show') }
function closeMenu(){ $('drawer').classList.remove('open');$('overlay').classList.remove('show') }
function stats(){const animals=allAnimals().filter(x=>x.a.status!=='Archiv');const buy=animals.reduce((s,x)=>s+Number(x.a.buyPrice||0),0);const mv=animals.reduce((s,x)=>s+market(x.a),0);return {count:animals.length,buy,mv,archive:db.archive.length,nz:db.clutches.length,sales:db.sales.length};}
function renderHome(){const s=stats();$('overview').innerHTML=`<div class="grid"><div class="stat">Gesamtbestand<b>${s.count}</b></div><div class="stat">Kaufwert<b>${money(s.buy)}</b></div><div class="stat">Marktwert geschätzt<b>${money(s.mv)}</b></div><div class="stat">Differenz<b>${money(s.mv-s.buy)}</b></div></div><p class="muted">Marktwert ist eine konservative Schätzung aus Morph, Geschlecht und Einkaufspreis.</p>`;renderFoodOverview();renderRecent();}
function renderFoodOverview(){const items=(db.foodInventory||[]).filter(x=>Number(x.qty)>0);$('foodOverview').innerHTML=items.length?items.map(x=>`<div class="subcard"><b>${esc(x.name)}</b><br>Bestand: ${Number(x.qty||0)}</div>`).join(''):'<p class="muted">Kein Futterbestand eingetragen.</p>';}
function activitiesFor(a){let rows=[];(a.feeds||[]).forEach(f=>rows.push({d:f.date,t:`🍴 ${f.accepted===false?'Verweigert':'Gefressen'} ${f.amount?f.amount+'g ':''}${f.prey||''}`}));(a.sheds||[]).forEach(s=>rows.push({d:s.date,t:'🧤 Häutung'}));(a.weights||[]).forEach(w=>rows.push({d:w.date,t:`⚖️ ${w.weight}g`}));(a.photos||[]).forEach(p=>rows.push({d:p.date,t:'📷 Foto'}));return rows.sort((x,y)=>String(y.d).localeCompare(String(x.d)));}
function renderRecent(){let rows=[];allAnimals().forEach(({a})=>activitiesFor(a).forEach(r=>rows.push({d:r.d,t:`${nameOf(a)}: ${r.t}`})));rows.sort((a,b)=>String(b.d).localeCompare(String(a.d)));$('recent').innerHTML=rows.slice(0,10).map(r=>`<div class="listLine"><b>${esc(r.d||'-')}</b> ${esc(r.t)}</div>`).join('')||'<p class="muted">Noch keine Aktivitäten.</p>';}
function renderAnimals(t){const box=$(t+'List');if(!box)return;box.innerHTML=(db[t]||[]).map((a,i)=>animalCard(t,a,i)).join('')||'<p class="muted">Noch keine Tiere.</p>';}
function animalCard(t,a,i){const lastFeed=(a.feeds||[]).slice(-1)[0];const lastWeight=(a.weights||[]).slice(-1)[0];const cover=(a.photos||[])[0];return `<div class="animal">${cover?`<img src="${cover.data}" style="width:100%;max-height:220px;object-fit:cover;border-radius:14px;margin-bottom:10px">`:''}<h3>${esc(nameOf(a))}</h3><span class="pill">${esc(a.morph||'-')}</span><span class="pill">${esc(a.sex||'-')}</span><span class="pill">${esc(a.status||'-')}</span><br>${a.defaultFeeder?`🍽️ Standard: <b>${esc(a.defaultFeeder)}</b><br>`:''}💵 Kauf: ${money(a.buyPrice||0)} · Markt: ${money(market(a))}<br>${lastFeed?`🍴 Letzte Fütterung: ${esc(lastFeed.date)} ${lastFeed.accepted===false?'verweigert':'gefressen'}<br>`:''}${lastWeight?`⚖️ Gewicht: ${esc(lastWeight.weight)}g (${esc(lastWeight.date)})<br>`:''}<div class="btnRow"><button onclick="NGT.profile('${t}',${i})">📁 Tierakte</button><button onclick="NGT.edit('${t}',${i})">✏️ Bearbeiten</button><button onclick="NGT.qr('${t}',${i})">📱 QR-Code</button><button class="danger" onclick="NGT.remove('${t}',${i})">🗑️ Löschen</button></div></div>`}
function renderFoodPage(){const box=$('foodList');box.innerHTML=(db.foodInventory||[]).map((x,i)=>`<div class="subcard"><b>${esc(x.name)}</b><br>Bestand: ${Number(x.qty||0)}<div class="btnRow"><button onclick="NGT.foodEdit(${i})">✏️ Bearbeiten</button><button class="danger" onclick="NGT.foodDelete(${i})">🗑️ Löschen</button></div></div>`).join('')||'<p class="muted">Kein Futterbestand.</p>';}
function render(){normalize(db);renderHome();TYPES.forEach(renderAnimals);renderFoodPage();}
function addAnimal(t){editType=t;editIndex=null;openEditor({type:t,status:'Bestand'});}
function edit(t,i){editType=t;editIndex=i;openEditor(db[t][i]);}
function openEditor(a){$('modalTitle').textContent=editIndex===null?'Tier anlegen':'Tier bearbeiten';$('ae_name').value=a.name||'';$('ae_morph').value=a.morph||'';$('ae_weight').value=a.weight||'';$('ae_origin').value=a.origin||'';$('ae_birth').value=a.birth||a.birthDate||'';$('ae_buy').value=a.buyPrice||'';$('ae_price').value=a.price||'';$('ae_sex').value=a.sex||'Unbestimmt';$('ae_status').value=a.status||'Bestand';$('ae_feeder').innerHTML='<option value="">Kein Standard</option>'+PREY.map(p=>`<option ${p===(a.defaultFeeder||'')?'selected':''}>${p}</option>`).join('');$('ae_note').value=a.note||'';$('modal').classList.add('show');}
function closeEditor(){$('modal').classList.remove('show')}
function saveEditor(){const a={...(editIndex===null?{}:db[editType][editIndex])};a.uuid=a.uuid||uid();a.uid=a.uid||a.uuid;a.type=editType;a.name=$('ae_name').value.trim()||'Unbenannt';a.morph=$('ae_morph').value.trim();a.weight=$('ae_weight').value;a.origin=$('ae_origin').value.trim();a.birth=$('ae_birth').value;a.buyPrice=$('ae_buy').value;a.price=$('ae_price').value;a.sex=$('ae_sex').value;a.status=$('ae_status').value;a.defaultFeeder=$('ae_feeder').value;a.futterStandard=a.defaultFeeder;a.standardFeed=a.defaultFeeder;a.note=$('ae_note').value.trim();a.feeds=a.feeds||[];a.sheds=a.sheds||[];a.weights=a.weights||[];a.photos=a.photos||[];if(editIndex===null)db[editType].push(a);else db[editType][editIndex]=a;closeEditor();save();}
function remove(t,i){if(confirm('Tier wirklich löschen?')){db[t].splice(i,1);save();}}
function profile(t,i){profileType=t;profileIndex=i;activeTab='overview';renderProfile();$('profileModal').classList.add('show');}
function closeProfile(){$('profileModal').classList.remove('show');profileType=null;profileIndex=null;}
function tab(tab){activeTab=tab;renderProfile();}
function renderProfile(){if(profileType===null)return;const a=db[profileType][profileIndex];$('profileTitle').textContent=nameOf(a);$('profileSub').innerHTML=`${esc(a.morph||'-')} · ${esc(a.sex||'-')} · ${esc(a.status||'-')}<br>UUID: <span class="muted">${esc(a.uuid)}</span>`;document.querySelectorAll('.profileTab').forEach(b=>b.classList.remove('ok'));const btn=$('tab_'+activeTab);if(btn)btn.classList.add('ok');if(activeTab==='overview')renderProfileOverview(a);if(activeTab==='timeline')renderProfileTimeline(a);if(activeTab==='feeds')renderProfileFeeds(a);if(activeTab==='sheds')renderProfileSheds(a);if(activeTab==='weights')renderProfileWeights(a);if(activeTab==='photos')renderProfilePhotos(a);if(activeTab==='qr')renderProfileQr(a);}
function renderProfileOverview(a){const lastFeed=(a.feeds||[]).slice(-1)[0];const lastWeight=(a.weights||[]).slice(-1)[0];$('profileBody').innerHTML=`<div class="grid"><div class="stat">Marktwert<b>${money(market(a))}</b></div><div class="stat">Kaufwert<b>${money(a.buyPrice||0)}</b></div><div class="stat">Gewicht<b>${esc((lastWeight&&lastWeight.weight)||a.weight||'-')}g</b></div><div class="stat">Fotos<b>${(a.photos||[]).length}</b></div></div><div class="subcard">🍽️ Standardfutter: <b>${esc(a.defaultFeeder||'nicht gesetzt')}</b><br>🍴 Letzte Fütterung: ${lastFeed?esc(lastFeed.date)+' '+(lastFeed.accepted===false?'verweigert':'gefressen'):'-'}</div><div class="subcard"><b>Notizen</b><br>${esc(a.note||'Keine Notizen')}</div>`;}
function renderProfileTimeline(a){const rows=activitiesFor(a);$('profileBody').innerHTML=rows.map(r=>`<div class="listLine"><b>${esc(r.d||'-')}</b><br>${esc(r.t)}</div>`).join('')||'<p class="muted">Noch keine Einträge.</p>';}
function renderProfileFeeds(a){$('profileBody').innerHTML=`<div class="subcard"><h3>🍴 Fütterung hinzufügen</h3><input id="pfDate" type="date"><select id="pfPrey">${PREY.map(p=>`<option ${p===a.defaultFeeder?'selected':''}>${p}</option>`).join('')}</select><select id="pfStatus"><option value="gefressen">Gefressen</option><option value="verweigert">Verweigert</option></select><button onclick="NGT.profileAddFeed()">Speichern</button></div>`+(a.feeds||[]).slice().reverse().map(f=>`<div class="listLine"><b>${esc(f.date)}</b> ${f.accepted===false?'Verweigert':'Gefressen'} ${f.amount?esc(f.amount)+'g ':''}${esc(f.prey||'')}</div>`).join('');}
function renderProfileSheds(a){$('profileBody').innerHTML=`<div class="subcard"><h3>🧤 Häutung hinzufügen</h3><input id="psDate" type="date"><button onclick="NGT.profileAddShed()">Speichern</button></div>`+(a.sheds||[]).slice().reverse().map(s=>`<div class="listLine"><b>${esc(s.date)}</b> Häutung ${s.complete===false?'unvollständig':'vollständig'}</div>`).join('');}
function renderProfileWeights(a){$('profileBody').innerHTML=`<div class="subcard"><h3>⚖️ Gewicht hinzufügen</h3><input id="pwDate" type="date"><input id="pwValue" type="number" placeholder="Gewicht in g"><button onclick="NGT.profileAddWeight()">Speichern</button></div>`+(a.weights||[]).slice().reverse().map(w=>`<div class="listLine"><b>${esc(w.date)}</b> ${esc(w.weight)}g</div>`).join('');}
function renderProfilePhotos(a){$('profileBody').innerHTML=`<div class="subcard"><h3>📷 Foto hinzufügen</h3><input id="photoDate" type="date"><input id="photoNote" placeholder="Notiz"><input id="photoFile" type="file" accept="image/*"><button onclick="NGT.profileAddPhoto()">Foto speichern</button></div><div class="grid">`+(a.photos||[]).map((p,i)=>`<div class="subcard"><img src="${p.data}" style="width:100%;border-radius:12px;max-height:220px;object-fit:cover"><b>${esc(p.date||'-')}</b><br>${esc(p.note||'')}<button class="danger" onclick="NGT.deletePhoto(${i})">Foto löschen</button></div>`).join('')+'</div>';}
function renderProfileQr(a){$('profileBody').innerHTML='<div class="qrBox"><div id="profileQr"></div><div>'+esc(a.uuid)+'</div></div>';setTimeout(()=>{if(window.QRCode){$('profileQr').innerHTML='';new QRCode($('profileQr'),{text:a.uuid,width:220,height:220});}},0);}
function currentAnimal(){return db[profileType][profileIndex];}
function profileAddFeed(){const a=currentAnimal();const date=$('pfDate').value||new Date().toISOString().slice(0,10);const p=parseFeeder($('pfPrey').value||a.defaultFeeder);const accepted=$('pfStatus').value!=='verweigert';a.feeds.push({date,prey:p.prey,amount:p.amount,accepted});a.feeds.sort(byDate);reduceFood(`${p.amount}g ${p.prey}`,1);save();activeTab='feeds';renderProfile();}
function profileAddShed(){const a=currentAnimal();const date=$('psDate').value||new Date().toISOString().slice(0,10);a.sheds.push({date,complete:true});a.sheds.sort(byDate);save();activeTab='sheds';renderProfile();}
function profileAddWeight(){const a=currentAnimal();const date=$('pwDate').value||new Date().toISOString().slice(0,10);const weight=Number($('pwValue').value||0);if(!weight)return alert('Gewicht fehlt');a.weights.push({date,weight});a.weights.sort(byDate);a.weight=weight;save();activeTab='weights';renderProfile();}
function profileAddPhoto(){const a=currentAnimal();const file=$('photoFile').files[0];if(!file)return alert('Bitte Foto auswählen');const reader=new FileReader();reader.onload=function(){a.photos=a.photos||[];a.photos.unshift({id:uid(),date:$('photoDate').value||new Date().toISOString().slice(0,10),note:$('photoNote').value||'',data:reader.result});save();activeTab='photos';renderProfile();};reader.readAsDataURL(file);}
function deletePhoto(i){if(confirm('Foto löschen?')){currentAnimal().photos.splice(i,1);save();activeTab='photos';renderProfile();}}
function openLog(t,i){profile(t,i);activeTab='timeline';renderProfile();}
function closeLog(){$('logModal')?.classList.remove('show')}
function addFeed(){profileAddFeed()}
function addShed(){profileAddShed()}
function addWeight(){profileAddWeight()}
function parseFeeder(s){const m=String(s||'').match(/(Ratte|Maus|ASF|Küken|Heimchen|Schabe)\s*(\d+)?g?/i)||String(s||'').match(/(\d+)\s*g\s*(Ratte|Maus|ASF|Küken|Heimchen|Schabe)/i);if(!m)return {prey:'Ratte',amount:0};if(isNaN(Number(m[1])))return {prey:m[1],amount:Number(m[2]||0)};return {prey:m[2],amount:Number(m[1]||0)};}
function reduceFood(name,n){const item=(db.foodInventory||[]).find(x=>x.name===name);if(item)item.qty=Math.max(0,Number(item.qty||0)-n);}
function foodAdd(){const name=$('foodName').value.trim();const qty=Number($('foodQty').value||0);if(!name)return;const item=db.foodInventory.find(x=>x.name===name);if(item)item.qty=qty;else db.foodInventory.push({name,qty});$('foodName').value='';$('foodQty').value='';save();}
function foodEdit(i){const x=db.foodInventory[i];const q=prompt('Bestand',x.qty);if(q!==null){x.qty=Number(q||0);save();}}
function foodDelete(i){if(confirm('Futterbestand löschen?')){db.foodInventory.splice(i,1);save();}}
function qr(t,i){const a=db[t][i];$('qrTitle').textContent=a.name+' QR-Code';$('qrCode').innerHTML='';$('qrText').textContent=a.uuid;if(window.QRCode)new QRCode($('qrCode'),{text:a.uuid,width:220,height:220});else $('qrCode').textContent=a.uuid;$('qrModal').classList.add('show');}
function findQr(){const v=$('qrSearchId').value.trim();const hit=allAnimals().find(x=>x.a.uuid===v||x.a.uid===v||x.a.name===v);$('qrSearchResult').innerHTML=hit?animalCard(hit.t,hit.a,hit.i):'<p class="muted">Tier nicht gefunden.</p>';}
function search(){const q=$('globalSearch').value.toLowerCase();const rows=allAnimals().filter(x=>JSON.stringify(x.a).toLowerCase().includes(q));$('searchResults').style.display=q?'block':'none';$('searchResults').innerHTML=rows.map(x=>animalCard(x.t,x.a,x.i)).join('')||'Keine Treffer';}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ng-terrarium-backup.json';a.click();}
function importData(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{db=normalize(JSON.parse(r.result));save();alert('Import erfolgreich');}catch(e){alert('Import fehlgeschlagen')}};r.readAsText(file);}
window.NGT={setPage,openMenu,closeMenu,addAnimal,edit,remove,saveEditor,closeEditor,profile,closeProfile,tab,profileAddFeed,profileAddShed,profileAddWeight,profileAddPhoto,deletePhoto,openLog,closeLog,addFeed,addShed,addWeight,foodAdd,foodEdit,foodDelete,qr,findQr,search,exportData,importData};
document.addEventListener('DOMContentLoaded',()=>{const fp=$('feedPrey');if(fp)PREY.forEach(p=>fp.insertAdjacentHTML('beforeend',`<option>${p}</option>`));render();});
})();