(function(){
'use strict';
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').trim();}
function tokens(s){return norm(s).replace(/[^a-z0-9äöüß]+/gi,' ').split(/\s+/).filter(Boolean);}
function levenshtein(a,b){a=norm(a);b=norm(b);const dp=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)dp[i][0]=i;for(let j=0;j<=b.length;j++)dp[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return dp[a.length][b.length];}
function dateFromText(text){const l=norm(text);const today=new Date();function iso(d){return d.toISOString().slice(0,10)}if(/\bheute\b/.test(l))return iso(today);if(/\bgestern\b/.test(l)){const d=new Date(today);d.setDate(d.getDate()-1);return iso(d)}if(/\bvorgestern\b/.test(l)){const d=new Date(today);d.setDate(d.getDate()-2);return iso(d)}const days={montag:1,dienstag:2,mittwoch:3,donnerstag:4,freitag:5,samstag:6,sonntag:0};const mday=l.match(/letzten?\s+(montag|dienstag|mittwoch|donnerstag|freitag|samstag|sonntag)/);if(mday){const target=days[mday[1]];const d=new Date(today);let diff=(d.getDay()-target+7)%7;if(diff===0)diff=7;d.setDate(d.getDate()-diff);return iso(d)}const m=String(text||'').match(/(\d{1,2})[.\-/](\d{1,2})(?:[.\-/](\d{2,4}))?/);if(m){const y=m[3]?(m[3].length===2?'20'+m[3]:m[3]):String(today.getFullYear());return y+'-'+m[2].padStart(2,'0')+'-'+m[1].padStart(2,'0')}return ''}
function grams(text){const m=String(text||'').match(/(\d+(?:[,.]\d+)?)\s*(?:g|gramm|gr)\b/i);return m?Number(m[1].replace(',','.')):0}
function explicitPrey(text){return /(ratte|ratten|maus|mäuse|maeuse|asf|küken|kueken|heimchen|schabe|schaben)/i.test(String(text||''))}
function preyNorm(prey){prey=String(prey||'').toLowerCase();prey=prey.replace('ratten','Ratte').replace('ratte','Ratte').replace('maus','Maus').replace('mäuse','Maus').replace('maeuse','Maus').replace('kueken','Küken').replace('küken','Küken').replace('schaben','Schabe').replace('schabe','Schabe').replace('heimchen','Heimchen').replace('asf','ASF');return prey}
function feeder(text){let s=String(text||'');let m=s.match(/\b\d+\s*x?\s*(ratten|mäuse|maeuse|maus|asf|küken|kueken|heimchen|schaben|schabe)\b.*?(\d+(?:[,.]\d+)?)\s*(?:g|gramm|gr)\b/i);if(m)return Number(m[2].replace(',','.'))+'g '+preyNorm(m[1]);m=s.match(/(\d+(?:[,.]\d+)?)\s*(?:g|gramm|gr)?\s*(ratte|ratten|maus|mäuse|maeuse|asf|küken|kueken|heimchen|schabe|schaben)/i);if(!m)m=s.match(/(ratte|ratten|maus|mäuse|maeuse|asf|küken|kueken|heimchen|schabe|schaben)\s*(\d+(?:[,.]\d+)?)\s*(?:g|gramm|gr)?/i);if(!m)return '';let amount,prey;if(isNaN(Number(m[1].replace(',','.')))){prey=m[1];amount=Number(m[2].replace(',','.'))}else{amount=Number(m[1].replace(',','.'));prey=m[2]}return amount+'g '+preyNorm(prey)}
function stockQty(text){const s=String(text||'');let m=s.match(/\b(\d+)\s*x?\s*(?:ratten|mäuse|maeuse|maus|asf|küken|kueken|heimchen|schaben|schabe)\b/i);if(m)return {mode:/gekauft|geliefert|bekommen|erhalten|dazu|plus|erhöhe|erhoehe/.test(norm(s))?'add':'set',qty:Number(m[1])};m=s.match(/(?:gekauft|geliefert|bekommen|erhalten|plus|erhöhe|erhoehe|um|\+)\s*(\d+)/i);if(m)return {mode:'add',qty:Number(m[1])};m=s.match(/(?:minus|abziehen|verbraucht|\-)\s*(\d+)/i);if(m)return {mode:'add',qty:-Number(m[1])};m=s.match(/(?:bestand|noch|auf|=|setze)\s*(?:auf\s*)?(\d+)/i);if(m)return {mode:'set',qty:Number(m[1])};m=s.match(/^(?:\d+(?:[,.]\d+)?\s*(?:g|gramm|gr)\s*(?:ratte|ratten|maus|mäuse|maeuse|asf|küken|kueken|heimchen|schabe|schaben)?|(?:ratte|ratten|maus|mäuse|maeuse|asf|küken|kueken|heimchen|schabe|schaben)\s*\d+(?:[,.]\d+)?\s*(?:g|gramm|gr)?)\s+(\d+)\s*$/i);if(m)return {mode:'set',qty:Number(m[1])};return {mode:'add',qty:0}}
function stockLike(text){const s=String(text||'').trim();const l=norm(s);if(/futterbestand|bestand|vorrat|lager|setze|erhöhe|erhoehe|auf|=|plus|minus|gekauft|geliefert|bekommen|erhalten|noch|\+|\-/.test(l)&&grams(s))return true;if(/^\d+(?:[,.]\d+)?\s*(?:g|gramm|gr)\s+\d+\s*$/.test(l))return true;if(/^(ratte|maus|asf|küken|kueken|heimchen|schabe)\s*\d+(?:[,.]\d+)?\s*(?:g|gramm|gr)?\s+\d+\s*$/.test(l))return true;if(/\b\d+\s*x?\s*(ratten|mäuse|maeuse|maus|asf|küken|kueken|heimchen|schaben|schabe)\b.*\d+\s*(g|gramm|gr)/i.test(s))return true;return false}
function animalNameGuess(text){let s=String(text||'');s=s.replace(/\d{1,2}[.\-/]\d{1,2}(?:[.\-/]\d{2,4})?/g,' ');s=s.replace(/\d+(?:[,.]\d+)?\s*(?:g|gramm|gr)?\s*(ratte|ratten|maus|mäuse|maeuse|asf|küken|kueken|heimchen|schabe|schaben)?/ig,' ');s=s.replace(/heute|gestern|vorgestern|letzten|montag|dienstag|mittwoch|donnerstag|freitag|samstag|sonntag|hat|wurde|ist|wiegt|jetzt|aktuell|gewicht|gehäutet|gehaeutet|häutung|haeutung|komplett|gefüttert|gefuttert|gefressen|frass|fraß|bekam|bekommen|verweigert|angenommen|abgelehnt|nicht|wollte|frisst|standardfutter|standard|futter|futterbestand|bestand|vorrat|lager|plus|minus|setze|erhöhe|erhoehe|auf|gekauft|geliefert|erhalten|noch|habe|ich/ig,' ');return s.trim().split(/\s+/)[0]||''}
function findAnimal(text){const q=norm(text);const all=NGTStore.allAnimals();let best=null;for(const item of all){const names=[item.a.name,item.a.displayId,item.a.uid,item.a.uuid].filter(Boolean);for(const name of names){const n=norm(name);if(!n)continue;if(q===n||q.includes(n)||n.includes(q)){return {...item,score:0}}for(const tk of tokens(q)){const dist=levenshtein(tk,n);const limit=n.length<=5?1:2;if(dist<=limit&&(!best||dist<best.score))best={...item,score:dist};}}}return best}
function hasAnimal(text){return !!(findAnimal(text)||findAnimal(animalNameGuess(text)))}
function intent(text){const l=norm(text);if(stockLike(text))return 'stock';if(/standardfutter|standard futter|futtergroesse|futtergröße/.test(l))return 'defaultFeeder';if(/gehäutet|gehaeutet|haut|häutung|haeutung|shed/.test(l))return 'shed';if(/verweigert|nicht gefressen|wollte nicht|frisst nicht|nicht angenommen|abgelehnt|wollte.*nicht/.test(l))return 'feed_refused';if(/wiegt|gewicht|waage/.test(l)&&grams(text))return 'weight';if(hasAnimal(text)&&grams(text)&&!explicitPrey(text)&&!/gefressen|gefuttert|gefüttert|frass|fraß|angenommen|futter bekommen|bekam|gefüttert/.test(l))return 'weight';if(/gefressen|gefuttert|gefüttert|frass|fraß|angenommen|futter bekommen|bekam|bekommen/.test(l))return 'feed';if(feeder(text)&&hasAnimal(text))return 'feed';if(dateFromText(text)&&hasAnimal(text))return 'feed';if(grams(text)&&!explicitPrey(text))return 'weight';return 'unknown'}
function parseLine(line,current){const inText=String(line||'').trim();const it=intent(inText);const found=it==='stock'?null:(findAnimal(inText)||findAnimal(animalNameGuess(inText))||current||null);return {raw:inText,intent:it,date:dateFromText(inText)||NGT500.today(),grams:grams(inText),feeder:feeder(inText),stock:stockQty(inText),animal:found,animalGuess:animalNameGuess(inText)}}
function parse(text){let current=null;const out=[];String(text||'').split(/\n|;/).map(x=>x.trim()).filter(Boolean).forEach(line=>{const direct=findAnimal(line);if(direct&&intent(line)==='unknown'){current=direct;out.push({raw:line,intent:'context',animal:direct});return;}const p=parseLine(line,current);if(p.animal)current=p.animal;out.push(p);});return out}
window.NGTAIEngine={norm,tokens,levenshtein,dateFromText,grams,explicitPrey,feeder,stockLike,stockQty,intent,findAnimal,animalNameGuess,parseLine,parse};
})();
