(function(){
'use strict';
function daysSince(date){return AnimalEngine.daysSinceOr(date,9999)}
function latest(list){return AnimalEngine.latest(list)}
function avgInterval(list){const arr=(list||[]).map(x=>x.date).filter(Boolean).sort();if(arr.length<2)return 0;let sum=0,c=0;for(let i=1;i<arr.length;i++){const a=Date.parse(arr[i-1]),b=Date.parse(arr[i]);if(a&&b){sum+=(b-a)/86400000;c++}}return c?Math.round(sum/c):0}
function animalSummary(a){const lf=latest(a.feeds),lw=latest(a.weights),ls=latest(a.sheds),lh=latest(a.health);const feeds=(a.feeds||[]);const weights=AnimalEngine.sortHistory(a.weights,'asc');let trend='unbekannt';if(weights.length>=2){const diff=Number(weights[weights.length-1].weight||0)-Number(weights[weights.length-2].weight||0);trend=diff>0?'steigend (+'+diff+'g)':diff<0?'fallend ('+diff+'g)':'stabil'}return [a.name,'Gewicht: '+(lw?lw.weight+'g am '+lw.date:'-'),'Letzte Fütterung: '+(lf?lf.date+' '+(lf.accepted===false?'verweigert':'gefressen'):'-'),'Ø Futterintervall: '+(avgInterval(feeds)||'-')+' Tage','Letzte Häutung: '+(ls?ls.date:'-'),'Gewichtstrend: '+trend,'Gesundheit: '+(lh?(lh.status||'-')+' · '+(lh.title||lh.type||'Eintrag'):'unauffällig')].join('\n')}
function today(){const all=NGTStore.allAnimals().filter(x=>AnimalEngine.isActiveAnimal(x.a));const feed=[],weight=[],shed=[],critical=[];all.forEach(x=>{const a=x.a;const lf=latest(a.feeds),lw=latest(a.weights),ls=latest(a.sheds);const fd=daysSince(lf&&lf.date),wd=daysSince(lw&&lw.date),sd=daysSince(ls&&ls.date);if(CareRulesEngine.isFeedDue(a))feed.push(a.name+(lf?' · '+fd+' Tage':' · keine Fütterung'));if(CareRulesEngine.isWeightDue(a))weight.push(a.name+(lw?' · '+wd+' Tage':' · kein Gewicht'));if(ls&&sd>=45)shed.push(a.name+' · letzte Häutung vor '+sd+' Tagen');const recent=AnimalEngine.sortHistory(a.feeds,'desc').slice(0,3);if(recent.length>=2&&recent.slice(0,2).every(f=>f.accepted===false))critical.push(a.name+' · wiederholte Verweigerung');});const food=FoodInventoryEngine.sortInventory(NGTStore.data().foodInventory||[]).filter(f=>FoodInventoryEngine.needsRestock(f)).map(f=>f.name+' · Bestand '+FoodInventoryEngine.quantity(f));return {feed,weight,shed,critical,food}}
function renderToday(){const t=today();function box(title,arr){return `<div class="tc2SubCard"><b>${title}: ${arr.length}</b><br>${arr.length?arr.map(NGT500.esc).join('<br>'):'Keine Einträge.'}</div>`}return box('Heute füttern/prüfen',t.feed)+box('Gewicht aktualisieren',t.weight)+box('Häutung beobachten',t.shed)+box('Kritisch',t.critical)+box('Futter niedrig',t.food)}
function afterSave(p,a){if(!a)return '';if(p.intent==='weight'){const w=AnimalEngine.sortHistory(a.weights,'asc');if(w.length>=2){const diff=Number(w[w.length-1].weight||0)-Number(w[w.length-2].weight||0);return diff?' · Veränderung zur letzten Messung: '+(diff>0?'+':'')+diff+'g':' · Gewicht unverändert.'}return ' · Erste Gewichtsmessung gespeichert.'}
if(p.intent==='feed'||p.intent==='feed_refused'){const avg=avgInterval(a.feeds||[]);return avg?' · Ø Futterintervall: '+avg+' Tage.':''}
if(p.intent==='shed'){const avg=avgInterval(a.sheds||[]);return avg?' · Ø Häutungsintervall: '+avg+' Tage.':''}
return ''}
window.NGTAIManager={daysSince,latest,avgInterval,animalSummary,today,renderToday,afterSave};
})();
