(function(){
'use strict';
const META_KEY='terracontrol_cloud_meta_v1';
const LAST_KEY='terracontrol_cloud_last_backup_v1';
const TOKEN_KEY='terracontrol_drive_token_v1';
const CLIENT_KEY='terracontrol_google_client_id';
const DEFAULT_CLIENT='923995580181-vbtua7122vsh385e1bdp7vfuqd49m3q3.apps.googleusercontent.com';
const SCOPE='https://www.googleapis.com/auth/drive.file';
function load(k){try{return JSON.parse(localStorage.getItem(k)||'{}')||{}}catch(e){return {}}}
function save(k,o){localStorage.setItem(k,JSON.stringify(o||{}))}
function profile(){return load('tc_user_profile')}
function clientId(){return localStorage.getItem(CLIENT_KEY)||DEFAULT_CLIENT}
function stripPhotosAnimal(a){const copy=JSON.parse(JSON.stringify(a||{}));if(Array.isArray(copy.photos)){copy.photos=copy.photos.map(p=>({date:p.date||'',type:p.type||'',note:p.note||'',cover:!!p.cover,omitted:true}))}return copy}
function stripPhotosData(data){const d=JSON.parse(JSON.stringify(data||{}));['koenig','boas','geckos','spinnen'].forEach(k=>{if(Array.isArray(d[k]))d[k]=d[k].map(stripPhotosAnimal)});return d}
function collectLocalStorage(){const out={};Object.keys(localStorage).forEach(k=>{if(k.startsWith('terracontrol_')||k.startsWith('tc_')||k.startsWith('ngt_')){try{out[k]=JSON.parse(localStorage.getItem(k))}catch(e){out[k]=localStorage.getItem(k)}}});return out}
function packageData(){const p=profile();const raw=NGTStore.data?NGTStore.data():{};return {app:'TerraControl',type:'cloud-backup',version:'1.0',createdAt:new Date().toISOString(),user:{name:p.name||'',email:p.email||'',sub:p.sub||'',provider:p.provider||''},data:stripPhotosData(raw),localStorage:collectLocalStorage(),notes:'Fotos werden in Phase B.2 noch nicht als Bilddaten gesichert.'}}
function filename(){const dt=new Date().toISOString().replace(/[:.]/g,'-').slice(0,19);return 'TerraControl-Cloud-Backup-'+dt+'.json'}
function download(){const payload=packageData();const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename();document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);const meta={lastBackupAt:payload.createdAt,lastBackupType:'export',lastBackupName:a.download,user:payload.user};save(META_KEY,meta);save(LAST_KEY,payload);return meta}
function status(){return load(META_KEY)}
function restoreFromObject(obj){if(!obj||obj.app!=='TerraControl'){throw new Error('Kein TerraControl Backup.')}if(obj.data){localStorage.setItem('ngt_v500_data',JSON.stringify(obj.data));}if(obj.localStorage){Object.keys(obj.localStorage).forEach(k=>{try{localStorage.setItem(k,JSON.stringify(obj.localStorage[k]))}catch(e){}})}save(META_KEY,{lastRestoreAt:new Date().toISOString(),restoredBackupAt:obj.createdAt||'',lastBackupType:'restore',user:obj.user||{}});return true}
function importFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=function(){try{const obj=JSON.parse(String(r.result||'{}'));restoreFromObject(obj);resolve(obj)}catch(e){reject(e)}};r.onerror=reject;r.readAsText(file)})}
function loadGis(){return new Promise((resolve,reject)=>{if(window.google&&google.accounts&&google.accounts.oauth2){resolve();return;}const s=document.createElement('script');s.src='https://accounts.'+'google.com/gsi/client';s.async=true;s.defer=true;s.onload=resolve;s.onerror=()=>reject(new Error('Google API konnte nicht geladen werden.'));document.head.appendChild(s)})}
function requestToken(){return loadGis().then(()=>new Promise((resolve,reject)=>{try{const tokenClient=google.accounts.oauth2.initTokenClient({client_id:clientId(),scope:SCOPE,callback:function(r){if(r&&r.access_token){save(TOKEN_KEY,{access_token:r.access_token,createdAt:new Date().toISOString(),scope:SCOPE});resolve(r.access_token)}else reject(new Error('Kein Drive-Zugriff erhalten.'))}});tokenClient.requestAccessToken({prompt:'consent'})}catch(e){reject(e)}}))}
function token(){const t=load(TOKEN_KEY);return t.access_token||''}
function ensureToken(){return token()?Promise.resolve(token()):requestToken()}
function uploadToDrive(){const payload=packageData();const name=filename();const boundary='tc_boundary_'+Date.now();const meta={name:name,mimeType:'application/json'};const body='--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify(meta)+'\r\n--'+boundary+'\r\nContent-Type: application/json\r\n\r\n'+JSON.stringify(payload,null,2)+'\r\n--'+boundary+'--';return ensureToken().then(access=>fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart',{method:'POST',headers:{Authorization:'Bearer '+access,'Content-Type':'multipart/related; boundary='+boundary},body:body}).then(r=>{if(!r.ok)throw new Error('Drive Upload fehlgeschlagen: '+r.status);return r.json()})).then(file=>{const meta={lastBackupAt:payload.createdAt,lastBackupType:'google-drive',lastBackupName:name,driveFileId:file.id||'',user:payload.user};save(META_KEY,meta);save(LAST_KEY,payload);return meta})}
function listDriveBackups(){return ensureToken().then(access=>fetch("https://www.googleapis.com/drive/v3/files?q=name%20contains%20'TerraControl-Cloud-Backup-'%20and%20trashed%3Dfalse&orderBy=createdTime%20desc&pageSize=10&fields=files(id,name,createdTime,modifiedTime,size)",{headers:{Authorization:'Bearer '+access}}).then(r=>{if(!r.ok)throw new Error('Drive Liste fehlgeschlagen: '+r.status);return r.json()})).then(x=>x.files||[])}
function downloadDriveFile(id){return ensureToken().then(access=>fetch('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(id)+'?alt=media',{headers:{Authorization:'Bearer '+access}}).then(r=>{if(!r.ok)throw new Error('Drive Download fehlgeschlagen: '+r.status);return r.json()}))}
window.NGTCloudBackup={packageData,download,status,restoreFromObject,importFile,requestToken,uploadToDrive,listDriveBackups,downloadDriveFile};
})();