(function(){
'use strict';
function latest(list){return (list||[]).slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))[0]||null}
function daysSince(d){const t=Date.parse(d||'');return t?Math.floor((Date.now()-t)/86400000):9999}
function age(birth){const t=Date.parse(birth||'');if(!t)return '-';const y=Math.floor((Date.now()-t)/31557600000);return y>0?y+' J.':'<1 J.'}
function healthStatus(a){let score=0;const lf=latest(a.feeds),lw=latest(a.weights),lh=latest(a.health);const recent=(a.feeds||[]).slice().sort((p,q)=>String(q.date||'').localeCompare(String(p.date||''))).slice(0,3);if(recent.length>=2&&recent.slice(0,2).every(f=>f.accepted===false))score+=2;if(lw){const w=(a.weights||[]).slice().sort((p,q)=>String(p.date||'').localeCompare(String(q.date||'')));if(w.length>=2&&Number(w[w.length-1].weight)<Number(w[w.length-2].weight))score+=2}else score+=1;if(daysSince(lf&&lf.date)>=(Number(a.feedIntervalDays||a.feedingInterval||14)+7))score+=1;if(daysSince(lw&&lw.date)>=45)score+=1;if(lh&&String(lh.status||'').toLowerCase()!=='abgeschlossen')score+=1;if(score>=3)return {txt:'Handlung',icon:'🔴',cls:'danger'};if(score>=1)return {txt:'Beobachten',icon:'🟡',cls:'ok'};return {txt:'Gesund',icon:'🟢',cls:'ok'}}
function rel(date){const d=daysSince(date);if(d===9999)return '-';if(d===0)return 'heute';if(d===1)return 'gestern';return 'vor '+d+' Tagen'}
function animalCard(x){
 const a=x.a,esc=NGT500.esc;
 const lf=latest(a.feeds),lw=latest(a.weights),ls=latest(a.sheds),photo=(a.photos||[]).find(p=>p.cover)||(a.photos||[])[0],hs=healthStatus(a);
 const uid=encodeURIComponent(a.uuid||a.id||a.uid||'');
 const img=photo?`<img class="photo" src="${photo.data}">`:`<div class="subcard" style="text-align:center;padding:34px">📷<br>Titelbild hinzufügen</div>`;
 const weight=lw?esc(lw.weight)+' g':(a.weight?esc(a.weight)+' g':'-');
 return `<div class="animal ${hs.cls}">${img}<div style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start"><div><h2>${esc(a.name)}</h2><span class="pill">${esc(a.morph||'-')}</span><span class="pill">${esc(a.sex||'-')}</span></div><div class="pill">${hs.icon} ${esc(hs.txt)}</div></div><div class="grid" style="margin:10px 0"><div class="stat">Gewicht<b>${weight}</b></div><div class="stat">Alter<b>${esc(age(a.birth))}</b></div></div><div class="subcard">🍽 ${lf?rel(lf.date)+' · '+(lf.accepted===false?'verweigert':'gefressen'):'keine Fütterung'}<br>🧤 ${ls?rel(ls.date):'keine Häutung'}<br>⚖ ${lw?rel(lw.date):'kein Gewicht'}${a.defaultFeeder?`<br>🐀 Standard: <b>${esc(a.defaultFeeder)}</b>`:''}</div><div class="btnRow"><button onclick="NGT500.route('profile',{t:'${x.t}',i:${x.i}})">Tierpass</button><button onclick="NGT500.route('profile',{t:'${x.t}',i:${x.i},tab:'photos'})">Foto</button><button onclick="NGT500.route('profile',{t:'${x.t}',i:${x.i},tab:'feeds'})">Fütterung</button><button onclick="NGT500.route('profile',{t:'${x.t}',i:${x.i},tab:'sheds'})">Häutung</button><button onclick="NGT500.route('profile',{t:'${x.t}',i:${x.i},tab:'weights'})">Gewicht</button><button onclick="location.href='./abgabe.html?id=${uid}'">PDF</button><button onclick="NGT500.route('animals',{t:'${x.t}',edit:${x.i}})">Bearbeiten</button><button onclick="NGT500.route('profile',{t:'${x.t}',i:${x.i},tab:'qr'})">QR</button><button class="danger" onclick="NGTAnimals.remove('${x.t}',${x.i})">Löschen</button></div></div>`
}
function list(rows){return rows.length?rows.map(r=>`<div class="listLine"><b>${NGT500.esc(r.d||'-')}</b> ${NGT500.esc(r.txt||'')}</div>`).join(''):'<p class="muted">Keine Einträge.</p>'}
function timeline(a){let rows=[];if(a.birth)rows.push({d:a.birth,txt:'Schlupf'});if(a.acquiredDate)rows.push({d:a.acquiredDate,txt:'Erworben'});(a.feeds||[]).forEach(f=>rows.push({d:f.date,txt:`${f.accepted===false?'Verweigert':'Gefressen'} ${f.amount?f.amount+'g ':''}${f.prey||''}`}));(a.sheds||[]).forEach(s=>rows.push({d:s.date,txt:'Häutung'}));(a.weights||[]).forEach(w=>rows.push({d:w.date,txt:`Gewicht ${w.weight}g`}));(a.photos||[]).forEach(p=>rows.push({d:p.date,txt:`Foto ${p.type||''} ${p.note||''}`}));return rows.sort((x,y)=>String(y.d).localeCompare(String(x.d)))}
window.NGTUI={animalCard,list,timeline};
})();